### DISCUSSION TITLE
How to run Wazuh with a Docker macvlan?

### DISCUSSION THREAD

**Discussion by schneich** [wazuh/wazuh-docker#1394] [Q&A] [answered]
Dear community,

I have unsuccessfully spent 3 nights trying to get Wazuh running in single-mode, but with a more complex Docker network setup.

Goals:
- The Dashboard-Container should be accessible via a Docker **macvlan** (e.g. on IP 192.168.60.9)
- There should be a second, Docker-internal network for the communication between all three containers. (e.g. Dashboard 10.10.14.4, Indexer 10.10.14.3. and Manager 10.10.14.2)
- This setup makes sure that Wazuh-internal traffic stays within Docker and only the Dashboard is available in my LAN.

If you are interested in the details, have a look into the Docker documentation about [IPvlan 802.1Q trunk L2 mode example usage](https://docs.docker.com/network/drivers/ipvlan/#ipvlan-8021q-trunk-l2-mode-example-usage). (or if you have 40min time, this is the best [video about Docker Networking](https://www.youtube.com/watch?v=bKFMS5C4CG0).)

Questions:
- I need to change IP-addresses in specific places - but obviously, I struggle to find all of them. (e.g. when running the securityadmin.sh to change passwords, it tries something on localhost:9200, which will not work. But where can I change this to the IP 10.10.14.3?)
- User permission is a mess. I tried to make sure that user 1000:1000 has access to everything, before starting the Docker-stack. But then, there are some access denied log entries and I am really not sure, where this is coming from.

If anybody has successfully deployed Wazuh with Docker and macvlan, I would very much appreciate, if you could share some insights.
Or if someone could point me to all the relevant places, if the IPs of all 3 containers are individually specified.

Chris

**Comment by schneich** [comment, marked as answer]
After many more hours, I have been able to solve it - with the help from the [docker community](https://forums.docker.com/t/change-folder-for-persisting-data-leads-to-folder-permission-errors/142128?u=schneich).

The root cause of all my issues was that I did not understand the difference between _Docker Volumes_ and _Docker bind mounts_. After changing my yml, it works perfectly fine.

- My yml utilises the Docker volume, combined with the mount-option, so that I don’t have to change my backup strategy.
- I was able to define my own network settings.
-- the containers talk to each other via an internal docker network
-- the dashboard container is accessible via its own IP-address
- I added a top level name, so that the Docker stack is not named after the folder, the compose.yml is sitting in.

Be aware that in the official wazuh-documentation, they use the old `docker-compose` command. For creating the ssl-certificates, this is fine, but for the wazuh containers itself, you should use `docker compose` (without the dash).

here is my finally working solution:

```
# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
name: wazuh

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.8.0
    container_name: manager
    hostname: wazuh.manager
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
      - TZ=Europe/Zurich
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      macvlan60:
        ipv4_address: 192.168.60.8
      backend:
        ipv4_address: 10.10.14.2



  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.8.0
    container_name: indexer
    hostname: wazuh.indexer
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - TZ=Europe/Zurich
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    networks:
      backend:
        ipv4_address: 10.10.14.3



  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.8.0
    container_name: dashboard
    hostname: wazuh.dashboard
    restart: unless-stopped
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
      - TZ=Europe/Zurich
    volumes:
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    depends_on:
      wazuh.indexer:
        condition: service_started
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager
    networks:
      macvlan60:
        ipv4_address: 192.168.60.9
      backend:
        ipv4_address: 10.10.14.4



# Volumes für die Persistierung von Daten (https://dev.to/rimelek/everything-about-docker-volumes-1ib0#custom-volume-path-overview)
volumes:
  wazuh_api_configuration:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_api_configuration
      o: bind
  wazuh_etc:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_etc
      o: bind
  wazuh_logs:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_logs
      o: bind
  wazuh_queue:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_queue
      o: bind
  wazuh_var_multigroups:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_var_multigroups
      o: bind
  wazuh_integrations:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_integrations
      o: bind
  wazuh_active_response:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_active_response
      o: bind
  wazuh_agentless:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_agentless
      o: bind
  wazuh_wodles:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/wazuh_wodles
      o: bind
  filebeat_etc:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/filebeat_etc
      o: bind
  filebeat_var:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/manager/filebeat_var
      o: bind
  wazuh-indexer-data:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/indexer/wazuh-indexer-data
      o: bind
  wazuh-dashboard-config:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/dashboard/wazuh-dashboard-config
      o: bind
  wazuh-dashboard-custom:
    driver: local
    driver_opts:
      type: none
      device: /home/uadmin/Docker/Wazuh/wazuh-docker/single-node/config/dashboard/wazuh-dashboard-custom
      o: bind


# Network specifications
networks:
  macvlan60:
    external: true
  backend:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "10.10.14.0/24"
```

**Comment by schneich** [comment]
note: github is not the right place to ask these questions. There is a very active google group. Try your luck there: https://groups.google.com/g/wazuh

**Reply by gjherrmann** [reply]
Thank you for including the reference here for assigning a static mount point for volumes and also referring the google group mailing list.

I have only previously, in compose files, set the mount point for each container in the following manner rather than as a separate instance after all the services are defined.

```
services:
    wazuh.indexer:
        volumes:
             - /foo/bar/wazuh-indexer-data:/var/lib/wazuh-indexer
```
