### ISSUE TITLE
After following procedure - admin password not changed

### ISSUE THREAD

**Issue by TheChaser5** [wazuh/wazuh-docker#1307]
I followed this procedure:
https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-pwd-existing-usr

to change the password of admin

but somehow after done everyting, the default password stayed

is there a way to remove the read-only flag so I can JUST change the password.

Let me know what you need to help :)

**Comment by davidcr01** [comment]
Hello. I followed the steps you mentioned of the documentation and the password change worked for me. I leave you the steps I followed to compare it with your steps:

1. I stopped the Wazuh Docker deployment with `docker-compose down`
2. I run the `docker run --rm -ti wazuh/wazuh-indexer:4.7.3 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh` command to generate a new hash for the new password. I introduced the following password: `NewPassword1234`, and the script returned me the `$2y$12$r7dlj4vt6gbh9FXEocp3u.8N.yd7zn3N1rfP9dZAdCEX1PbfEwxLS` string.
3. I edited the `config/wazuh_indexer/internal_users.yml` file, removing the old hash of the admin user and replacing it with the new hash. Now, it looks like:
```yml
admin:
  hash: "$2y$12$r7dlj4vt6gbh9FXEocp3u.8N.yd7zn3N1rfP9dZAdCEX1PbfEwxLS"
  reserved: true
  backend_roles:
  - "admin"
  description: "Demo admin user"
```

4. I edited the `docker-compose.yml` file and replaced the two occurrences of the `INDEXER_PASSWORD` variable with my new password, `NewPassword1234`. The two occurrences are in the `wazuh.manager` and the `wauzh.dashboard` services:

```yml
services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.3
    hostname: wazuh.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=NewPassword1234

...

wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.3
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=NewPassword1234
```

5. I started the stack with the `docker-compose up -d` command and I entered to the Wazuh indexer container, you can access to it with the `docker exec -it <WAZUH_INDEXER_CONTAINER_NAME> bash` command, and you can get the `WAZUH_INDEXER_CONTAINER_NAME` with the `docker ps` command.
6. Inside the container, I run the following commands:
```console
export INSTALLATION_DIR=/usr/share/wazuh-indexer
CACERT=$INSTALLATION_DIR/certs/root-ca.pem
KEY=$INSTALLATION_DIR/certs/admin-key.pem
CERT=$INSTALLATION_DIR/certs/admin.pem
export JAVA_HOME=/usr/share/wazuh-indexer/jdk
```
7. Then, I run the following command to apply all the changes: `bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/wazuh-indexer/opensearch-security/ -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9200 -icl`

With this, If you navigate to the Wazuh dashboard in a new tab with the new credentials, it should work fine. To ensure this, you can try to delete the cache of the page or open a new Incognito window to enter the Wazuh dashboard.
