### ISSUE TITLE
Getting the desired certificates error when docker install wazuh

### ISSUE THREAD

**Issue by begize** [wazuh/wazuh-docker#1415]
HI everyone:
I installed docker according to the document and it is running normally, but an error occurs when getting the desired certificates. Can help me solve it?
The Linux version is ubuntu2404
-------------------------------------------------- -------------------------------------------------- ----------
mis@tguard:~/wazuh-docker/single-node$ sudo docker-compose -f generate-indexer-certs.yml run --rm generator
[+] Running 1/1
 ⠿Network single-node_default Created 0.9s
[+] Running 0/1
 ⠿ generatorError 1.8s
Error response from daemon: Head "https://registry-1.docker.io/v2/wazuh/wazuh-certs-generator/manifests/0.0.1": Get "https://auth.docker.io/token? scope=repository%3Awazuh%2Fwazuh-certs-generator%3Apull&service=registry.docker.io": read tcp 192.168.28.184:56392->34.226.69.105:443: read: connection reset by peer

-------------------------------------------------- -------------------------------------------------- ----------

**Comment by fabrizio8** [comment]
I'm also on 2404 but I'm having trouble just getting the basic images up.
Did you also follow [this doc](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html)? I feel like I am missing something.

https://github.com/wazuh/wazuh-docker/issues/1423

**Comment by rauldpm** [comment]
Hello @begize , sorry for the late response.

Do you still have the problem?

Apparently, this problem is related to a connectivity issue, please make sure that your firewall is configured correctly to allow the connection, in case you are using a proxy, you will need to configure it as follows, as we state in the documentation https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#single-node-deployment (this also applies for a multi-node deployment)

```
# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
version: '3'

services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
    environment:
      - HTTP_PROXY=YOUR_PROXY_ADDRESS_OR_DNS
```
      
I see that you are trying to pull revision `0.0.1`, when the current version of 4.8.0 is `0.0.2`, what version of Wazuh are you using? Did you update the repository as indicated in the documentation to maintain custom files? I will open an issue to change the `0.0.1` reference in the documentation but I couldn't reproduce your problem using 0.0.2 and 0.0.1, so it must be a connection issue.
