### ISSUE TITLE
Add configuration to Wazuh-Elasticsearch for Elasticsearch cluster

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-docker#145]
Hello team,

Since we use our Elasticsearch custom image we can not deploy an Elasticsearch Cluster. 

Previously it was enough to add certain environment variables in our deployment file, but now that solution is not valid.

Before:

```
elastic+     1  0.4 19.6 3191704 794016 ?      Ssl  08:46   1:19 /opt/jdk-11.0.1/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.io.tmpdir=/tmp/elasticsearch.GMIqfIH8 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Djava.locale.providers=COMPAT -XX:UseAVX=2 -Des.cgroups.hierarchy.override=/ -Xms512m -Xmx512m -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/usr/share/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=tar -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -Ecluster.name=wazuh -Ediscovery.zen.ping.unicast.hosts=wazuh-elasticsearch -Enode.data=true -Enode.master=true -Enode.name=wazuh-elasticsearch-0 -Enetwork.host=0.0.0.0 -Ediscovery.zen.minimum_master_nodes=2 -Ebootstrap.memory_lock=false -Enode.ingest=false
```

After: 

```
elastic+     1  3.1  3.9 7056572 2475968 ?     Ssl  11:23   3:58 /opt/jdk-11.0.1/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.io.tmpdir=/tmp/elasticsearch.rQMNk9ux -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Djava.locale.providers=COMPAT -XX:UseAVX=2 -Xms2048m -Xmx2048m -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/usr/share/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=tar -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch
```

config options:

```
          env:
            - name: ES_JAVA_OPTS
              value: '-Xms2048m -Xmx2048m'
            - name: node.master
              value: 'true'
            - name: node.data
              value: 'true'
            - name: node.ingest
              value: 'false'
            - name: bootstrap.memory_lock
              value: 'false'
            - name: cluster.name
              value: wazuh
            - name: network.host
              value: 0.0.0.0
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.zen.ping.unicast.hosts
              value: "wazuh-elasticsearch"
            - name: discovery.zen.minimum_master_nodes
              value: "2"
            - name: XPACK_ML
              value: 'false' 
```

Best regards,

Alfonso Ruiz-Bravo
