### ISSUE TITLE
Error response from daemon: manifest for wazuh/wazuh-cert-tool:5.0.0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by fahadshery** [wazuh/wazuh-docker#1622]
Hi,

trying to create the certs as per the docs:

```
docker compose -f generate-certs.yml run --rm generator
```

but getting the following error:
```
Error response from daemon: manifest for wazuh/wazuh-cert-tool:5.0.0 not found: manifest unknown: manifest unknown
```

here is the yaml file:
```
---
services:
  generator:
    image: wazuh/wazuh-cert-tool:5.0.0
    hostname: wazuh-cert-tool
    container_name: wazuh-cert-tool
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
```
