### ISSUE TITLE
kibana Notwoking please update file 

### ISSUE THREAD

**Issue by vncloudsco** [wazuh/wazuh-docker#165]
Today I tried installing docker with this source code, I found out that you forgot to set the port for kibana

```
  kibana:
    image: wazuh/wazuh-kibana:3.9.0_6.7.2
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
```

I had to edit it to work

```
  kibana:
    image: wazuh/wazuh-kibana:3.9.0_6.7.1
    hostname: kibana
    restart: always
    ports:
      - "5061:5061"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
```

source code:
https://github.com/wazuh/wazuh-docker/blob/7c49e389a8a1f4790ccd9dc7f4f5ca365e5bc50c/docker-compose.yml#L48
