### ISSUE TITLE
4001 - [index_not_found_exception]

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-docker#167]
I receive the following error, which prevents the app from working, when initialize a docker stack on a swarm cluster:
 4001 - [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id=".wazuh-version" & index_uuid="_na_" & index=".wazuh-version" }

Any thoughts on why this is occurring?  The compose file is as follows:

```yaml
# Wazuh App Copyright (C) 2018 Wazuh Inc. (License GPLv2)
version: '3.4'
networks:
  back:
volumes:
  backup:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},nolock,soft,nfsvers=4,rw
      device: ":${BACKUP_PATH}"
services:
  wazuh:
    image: wazuh/wazuh:3.8.2_6.7.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        window: 120s
    hostname: wazuh-manager
    restart: always
    ports:
    - "1514:1514/udp"
    - "1515:1515"
    - "514:514/udp"
    - "55000:55000"
#    - "1516:1516"
    #volumes:
    #- /mnt/Data/wazuh/ossec-data:/var/ossec/data:Z
#    - my-path:/etc/postfix:Z
#    - my-path:/etc/filebeat
#    - my-custom-config-path/ossec.conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      back:
        aliases:
        - wazuh
  logstash:
    image: wazuh/wazuh-logstash:3.8.2_6.7.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        window: 120s
    hostname: logstash
#    volumes:
#    - my-path:/etc/logstash/conf.d:Z
    ports:
    - "5000:5000"
    environment:
    - LS_HEAP_SIZE=2048m
    networks:
      back:
        aliases:
        - logstash
  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.8.2_6.7.0
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    hostname: elasticsearch
    ports:
    - "9200:9200"
#    - "9300:9300"
    environment:
    - node.name=node-1
    - cluster.name=wazuh
    - network.host=0.0.0.0
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #volumes:
    #- /mnt/Data/wazuh/elasticsearch:/usr/share/elasticsearch/data
    networks:
      back:
        aliases:
        - elasticsearch
  kibana:
    image: wazuh/wazuh-kibana:3.8.2_6.7.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        window: 120s
    hostname: kibana
#    environment:
#    - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      back:
        aliases:
        - kibana
  nginx:
    #image: registry.litmusbluesoftware.local/litmusblue/wazuh-nginx:3.8.2_6.7.0
    image: wazuh/wazuh-nginx:3.8.2_6.7.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        window: 120s
    hostname: nginx
    environment:
    - NGINX_PORT=443
    networks:
      back:
        aliases:
        - nginx
    ports:
    - "80:80"
    - "443:443"
```
