### ISSUE TITLE
Persist Wazuh Agents data during container recreation

### ISSUE THREAD

**Issue by 0x18katyan** [wazuh/wazuh-docker#170]
Hey y'all, 
Thanks for the amazing work you guys have been doing, I just have a simple query. How do I persist data related to agents during container recreation? I had connected some agents to Wazuh but after some changes in the docker-compose.yml, no agents are showing in the Wazuh-App in Kibana, I think this has something to do with container recreation that happens after each changes in the compose file. Is there any way I can prevent this from happening as I am using Wazuh in place with some other services in a single docker-compose.yml which may be subject to updates in the future and I don't want to have to go through the same registration process everytime an update is applied.

Thanks in advance !
Regards,
Katyansun

**Comment by 0x18katyan** [comment]
Okay, I feel a bit stupid now. I read the documentation again and it states that mounting a volume to /var/ossec/data should be enough. I just want to confirm that it is and I will close this issue. Sorry for the inconvenience. : )

**Comment by manuasir** [comment]
Hello @0x18katyan ,

You're right. If you want the Wazuh data to persist, just attach the container `/var/ossec/data` to any folder in your host. For example, using `docker-compose`:
```
...
  wazuh:
    image: wazuh/wazuh:3.9.0_6.7.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash
    volumes:
      - /tmp/ossec/:/var/ossec/data/
...
```

I hope that helps.
As you mentioned above, I think we can close this issue. Don't hesitate to open a new one if you need it anytime, we will be glad to help you.

Regards
