### ISSUE TITLE
[BUG] SSL Certificates error (java.io.FilePermission)

### ISSUE THREAD

**Issue by anotherhadi** [wazuh/wazuh-docker#1727]
I can't run my docker-compose file because of a file permission error.

`Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/wazuh-indexer/certs/indexer.pem" "read")`
For debug, I set the perm for every file listed above to 777, still not working

```bash
$ pwd
/etc/wazuh
$ tree
 .
├──  certs
│   ├──  admin-key.pem
│   ├──  admin.pem
│   ├──  root-ca-manager.pem
│   ├──  root-ca.key
│   ├──  root-ca.pem
│   ├──  root-ca.srl
│   ├──  wazuh.dashboard-key.pem
│   ├──  wazuh.dashboard.pem
│   ├──  wazuh.indexer-key.pem
│   ├──  wazuh.indexer.pem
│   ├──  wazuh.manager-key.pem
│   └──  wazuh.manager.pem
├──  config
└──  docker-compose.yml
```

<details>
  <summary>Docker compose file</summary>

```yaml
# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.10.1
    hostname: wazuh.manager
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      INDEXER_URL: https://wazuh.indexer:9200
      INDEXER_USERNAME: admin
      INDEXER_PASSWORD: MyS3cr37P450r.*-.
      FILEBEAT_SSL_VERIFICATION_MODE: full
      SSL_CERTIFICATE_AUTHORITIES: /etc/ssl/root-ca.pem
      SSL_CERTIFICATE: /etc/ssl/filebeat.pem
      SSL_KEY: /etc/ssl/filebeat.key
      API_USERNAME: admin
      API_PASSWORD: MyS3cr37P450r.*-.
    volumes:
      - wazuh_api_configuration:/var/ossec/ap/etc/wazuh/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - /etc/wazuh/certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - /etc/wazuh/certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - /etc/wazuh/certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - /etc/wazuh/config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.10.1
    hostname: wazuh.indexer
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      bootstrap.memory_lock: "true"
      NODE_NAME: "wazuh.indexer"
      CLUSTER_INITIAL_MASTER_NODES: "wazuh.indexer"
      CLUSTER_NAME: "wazuh-cluster"
      PATH_DATA: /var/lib/wazuh-indexer
      PATH_LOGS: /var/log/wazuh-indexer
      HTTP_PORT: 9200-9299
      TRANSPORT_TCP_PORT: 9300-9399
      COMPATIBILITY_OVERRIDE_MAIN_RESPONSE_VERSION: "true"
      PLUGINS_SECURITY_SSL_HTTP_PEMCERT_FILEPATH: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      PLUGINS_SECURITY_SSL_HTTP_PEMKEY_FILEPATH: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
      PLUGINS_SECURITY_SSL_HTTP_PEMTRUSTEDCAS_FILEPATH: /usr/share/wazuh-indexer/certs/root-ca.pem
      PLUGINS_SECURITY_SSL_TRANSPORT_PEMCERT_FILEPATH: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      PLUGINS_SECURITY_SSL_TRANSPORT_PEMKEY_FILEPATH: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
      PLUGINS_SECURITY_SSL_TRANSPORT_PEMTRUSTEDCAS_FILEPATH: /usr/share/wazuh-indexer/certs/root-ca.pem
      PLUGINS_SECURITY_SSL_HTTP_ENABLED: "true"
      PLUGINS_SECURITY_SSL_TRANSPORT_ENFORCE_HOSTNAME_VERIFICATION: "false"
      PLUGINS_SECURITY_SSL_TRANSPORT_RESOLVE_HOSTNAME: "false"
      PLUGINS_SECURITY_AUTHCZ_ADMIN_DN: "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
      PLUGINS_SECURITY_CHECK_SNAPSHOT_RESTORE_WRITE_PRIVILEGES: "true"
      PLUGINS_SECURITY_ENABLE_SNAPSHOT_RESTORE_PRIVILEGE: "true"
      PLUGINS_SECURITY_NODES_DN: "CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
      PLUGINS_SECURITY_RESTAPI_ROLES_ENABLED: '["all_access", "security_rest_api_access"]'
      PLUGINS_SECURITY_SYSTEM_INDICES_ENABLED: "true"
      PLUGINS_SECURITY_SYSTEM_INDICES_INDICES: '[".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]'
      PLUGINS_SECURITY_ALLOW_DEFAULT_INIT_SECURITYINDEX: "true"
      CLUSTER_ROUTING_ALLOCATION_DISK_THRESHOLD_ENABLED: "false"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - /etc/wazuh/certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - /etc/wazuh/certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - /etc/wazuh/certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - /etc/wazuh/certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - /etc/wazuh/certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      #  if you need mount a custom opensearch.yml, uncomment the next line and delete the environment variables
      # - /etc/wazuh/config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.10.1
    hostname: wazuh.dashboard
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 443:5601
    environment:
      WAZUH_API_URL: https://wazuh.manager
      DASHBOARD_USERNAME: admin
      DASHBOARD_PASSWORD: MyS3cr37P450r.*-.
      API_USERNAME: admin
      API_PASSWORD: MyS3cr37P450r.*-.
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601
      OPENSEARCH_HOSTS: https://wazuh.indexer:9200
      OPENSEARCH_SSL_VERIFICATIONMODE: certificate
      OPENSEARCH_REQUESTHEADERSALLOWLIST: '["securitytenant","Authorization"]'
      OPENSEARCH_SECURITY_MULTITENANCY_ENABLED: "false"
      SERVER_SSL_ENABLED: "true"
      OPENSEARCH_SECURITY_READONLY_MODE_ROLES: '["kibana_read_only"]'
      SERVER_SSL_KEY: "/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
      SERVER_SSL_CERTIFICATE: "/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem"
      OPENSEARCH_SSL_CERTIFICATEAUTHORITIES: '["/usr/share/wazuh-dashboard/certs/root-ca.pem"]'
      UISETTINGS_OVERRIDES_DEFAULTROUTE: /app/wz-home
    volumes:
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazu/etc/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
      - /etc/wazuh/certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - /etc/wazuh/certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - /etc/wazuh/certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - /etc/wazuh/config/wazuh_dashboard/wazuh.yml:/wazuh-config-mount/data/wazuh/config/wazuh.yml
      #  if you need mount a custom opensearch-dashboards.yml, uncomment the next line and delete the environment variables
      # - /etc/wazuh/config/wazuh_dashboard/opensearch_dashboards.yml:/wazuh-config-mount/config/opensearch_dashboards.yml
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:
```

</details>

<details>
  <summary>Full docker logs</summary>

This is for the indexer, but I got basically the same error for the dashboard

```txt
  wazuh.indexer-1    | WARNING: A terminally deprecated method in java.lang.System has been called
wazuh.indexer-1    | WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/wazuh-indexer/lib/opensearch-2.16.0.jar)
wazuh.indexer-1    | WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
wazuh.indexer-1    | WARNING: System::setSecurityManager will be removed in a future release
wazuh.indexer-1    | [2025-02-17T11:11:39,141][INFO ][o.o.n.Node               ] [node-1] version[2.16.0], pid[1], build[rpm/7149046c7c9c64aa43e437826af0b8b0dcabd730/2025-01-15T11:02:52.707428Z], OS[Linux/6.13.1/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/21.0.3/21.0.3+9-LTS]
wazuh.indexer-1    | [2025-02-17T11:11:39,143][INFO ][o.o.n.Node               ] [node-1] JVM home [/usr/share/wazuh-indexer/jdk], using bundled JDK/JRE [true]
wazuh.indexer-1    | [2025-02-17T11:11:39,143][INFO ][o.o.n.Node               ] [node-1] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.security.manager=allow, -Djava.locale.providers=SPI,COMPAT, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-9270378158926833994, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/wazuh-indexer, -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.security.manager=allow, -Djava.util.concurrent.ForkJoinPool.common.threadFactory=org.opensearch.secure_sm.SecuredForkJoinWorkerThreadFactory, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=file:///usr/share/wazuh-indexer/opensearch-performance-analyzer/opensearch_security.policy, --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED, -Xms1g, -Xmx1g, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/usr/share/wazuh-indexer, -Dopensearch.path.conf=/usr/share/wazuh-indexer, -Dopensearch.distribution.type=rpm, -Dopensearch.bundled_jdk=true]
wazuh.indexer-1    | [2025-02-17T11:11:39,219][WARN ][o.a.l.i.v.VectorizationProvider] [node-1] Java vector incubator module is not readable. For optimal vector performance, pass '--add-modules jdk.incubator.vector' to enable Vector API.
wazuh.dashboard-1 exited with code 0
wazuh.dashboard-1  | An OpenSearch Dashboards keystore already exists. Overwrite? [y/N] Created OpenSearch Dashboards keystore in /usr/share/wazuh-dashboard/config/opensearch_dashboards.keystore
wazuh.indexer-1    | [2025-02-17T11:11:39,643][INFO ][o.o.s.s.t.SSLConfig      ] [node-1] SSL dual mode is disabled
wazuh.indexer-1    | [2025-02-17T11:11:39,643][INFO ][o.o.s.OpenSearchSecurityPlugin] [node-1] OpenSearch Config path is /usr/share/wazuh-indexer
wazuh.indexer-1    | [2025-02-17T11:11:39,755][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-1] JVM supports TLSv1.3
wazuh.indexer-1    | [2025-02-17T11:11:39,756][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-1] Config directory is /usr/share/wazuh-indexer/, from there the key- and truststore files are resolved relatively
wazuh.indexer-1    | [2025-02-17T11:11:39,768][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [node-1] uncaught exception in thread [main]
wazuh.indexer-1    | org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:185) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:172) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:138) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:104) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | Caused by: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:805) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:744) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:545) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:197) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:505) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:432) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	... 6 more
wazuh.indexer-1    | Caused by: java.lang.reflect.InvocationTargetException
wazuh.indexer-1    | 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:796) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:744) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:545) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:197) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:505) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:432) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	... 6 more
wazuh.indexer-1    | Caused by: org.opensearch.OpenSearchSecurityException: Error while initializing transport SSL layer from PEM: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/wazuh-indexer/certs/indexer.pem" "read")
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:484) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:298) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:204) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:252) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:315) ~[?:?]
wazuh.indexer-1    | 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:796) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:744) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:545) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:197) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:505) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:432) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	... 6 more
wazuh.indexer-1    | Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/wazuh-indexer/certs/indexer.pem" "read")
wazuh.indexer-1    | 	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:488) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.security.AccessController.checkPermission(AccessController.java:1071) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:742) ~[?:?]
wazuh.indexer-1    | 	at java.base/sun.nio.fs.UnixPath.checkRead(UnixPath.java:789) ~[?:?]
wazuh.indexer-1    | 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49) ~[?:?]
wazuh.indexer-1    | 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171) ~[?:?]
wazuh.indexer-1    | 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.nio.file.spi.FileSystemProvider.readAttributesIfExists(FileSystemProvider.java:1270) ~[?:?]
wazuh.indexer-1    | 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributesIfExists(UnixFileSystemProvider.java:191) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.nio.file.Files.isDirectory(Files.java:2319) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.checkPath(DefaultSecurityKeyStore.java:1126) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.resolve(DefaultSecurityKeyStore.java:276) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:454) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:298) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:204) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:252) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:315) ~[?:?]
wazuh.indexer-1    | 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
wazuh.indexer-1    | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:796) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:744) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:545) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:197) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:505) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:432) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181) ~[opensearch-2.16.0.jar:2.16.0]
wazuh.indexer-1    | 	... 6 more
wazuh.indexer-1    | uncaught exception in thread [main]
wazuh.indexer-1    | java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
wazuh.indexer-1    | Likely root cause: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/wazuh-indexer/certs/indexer.pem" "read")
wazuh.indexer-1    | 	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:488)
wazuh.indexer-1    | 	at java.base/java.security.AccessController.checkPermission(AccessController.java:1071)
wazuh.indexer-1    | 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
wazuh.indexer-1    | 	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:742)
wazuh.indexer-1    | 	at java.base/sun.nio.fs.UnixPath.checkRead(UnixPath.java:789)
wazuh.indexer-1    | 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49)
wazuh.indexer-1    | 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
wazuh.indexer-1    | 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
wazuh.indexer-1    | 	at java.base/java.nio.file.spi.FileSystemProvider.readAttributesIfExists(FileSystemProvider.java:1270)
wazuh.indexer-1    | 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributesIfExists(UnixFileSystemProvider.java:191)
wazuh.indexer-1    | 	at java.base/java.nio.file.Files.isDirectory(Files.java:2319)
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.checkPath(DefaultSecurityKeyStore.java:1126)
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.resolve(DefaultSecurityKeyStore.java:276)
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:454)
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:298)
wazuh.indexer-1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:204)
wazuh.indexer-1    | 	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:252)
wazuh.indexer-1    | 	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:315)
wazuh.indexer-1    | 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
wazuh.indexer-1    | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
wazuh.indexer-1    | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:796)
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:744)
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:545)
wazuh.indexer-1    | 	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:197)
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:505)
wazuh.indexer-1    | 	at org.opensearch.node.Node.<init>(Node.java:432)
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
wazuh.indexer-1    | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
wazuh.indexer-1    | 	<<<truncated>>>
wazuh.indexer-1    | For complete error details, refer to the log at /var/log/wazuh-indexer/wazuh-cluster.log
wazuh.indexer-1 exited with code 1  
```

</details>
