### ISSUE TITLE
Add Wazuh cluster configuration option

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-docker#175]
Hello team,

It is necessary to add the Wazuh cluster configuration option. Not to make mandatory the use of configuration maps in Kubernetes. 

We will establish an environment variable to know if it is necessary to apply the configuration of the cluster or not. We must consider the option that we will only modify the cluster if it has not been previously modified. If it has been previously modified, the changes should not be applied. 

Best regards,

Alfonso Ruiz-Bravo

**Comment by manuasir** [comment]
Since this can be done by mounting a [custom ossec.conf](https://documentation.wazuh.com/3.11/docker/container-usage.html#mount-custom-wazuh-configuration-files) this task is not needed. 
This is a quick example of a two nodes cluster using docker and the custom config mount:

```
  wazuh-worker:
    image: wazuh/wazuh:x_y
    hostname: wazuh-worker
    restart: always
    ports:
      - "1520:1514/tcp"
    volumes:
      - './worker-ossec.conf:/wazuh-config-mount/etc/ossec.conf'
```

Also, this resource can be useful to do so https://wazuh.com/blog/auto-scalable-wazuh-cluster-with-docker-compose/
