### ISSUE TITLE
How to use emailnotification within this docker image

### ISSUE THREAD

**Issue by GammaPi** [wazuh/wazuh-docker#193]
Using a commercial email service for email alert message often requires authentication. If wazuh is deployed natively, I can use postfix as relay server. What should I do if I use docker to deploy wazuh.

**Comment by manuasir** [comment]
Hello @GammaPi ,

As you can see in the Wazuh Dockerfile:
https://github.com/wazuh/wazuh-docker/blob/7a6c3f5f5e8b1d76242e6adabd48267b7fa34598/wazuh/Dockerfile#L14-L22
The Postfix service is already built along with the Wazuh manager image, so it'd be the same process as configuring it natively.
Additionally to that, if you want the Postfix data and configuration to persist, you have the option of attaching a volume to the `/etc/postfix` folder. This could be an example in a `docker-compose.yml` file:

```
  wazuh:
    image: wazuh/wazuh:3.9.2_7.1.1
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - '/mnt/persistent/postfix:/etc/postfix'
```

Where `/mnt/persistent/postfix` would be your directory in your file system where the Postfix data would be mounted. 

I hope that helps.

Regards

**Comment by manuasir** [comment]
Hello @GammaPi ,

I just wanted to follow up this. Was that helpful for you? Let me know if you still face this problem. Otherwise, this issue can be closed.

Cheers

**Comment by GammaPi** [comment]
Thanks for your reply. I should check the Dockerfile by myself.

**Comment by airdogvan** [comment]
It took me a good while but I figured out the same solution, i.e. mounting a copy of the local postfix directory.

Maybe mention it in the official docs?  Cause for an alert system emails are kind of REALLY important...

**Comment by xr09** [comment]
Hi @airdogvan 

Our current recomendation on this would be to use a dedicated container as a mail relay, the docs will look a lot like the following:


#### SMTP Relay

Wazuh expects an SMTP relay in the config, usually on a VM you can install it on the same host (as it's stated on the docs), but in a container environment an individual service is recommended.

We'll use this docker image as the recommended for SMTP relay but users can pick their own as well.

- https://hub.docker.com/r/eeacms/postfix

The role of a SMTP relay is to forward the mail notifications from Wazuh to a valid mail server, in this example we're accepting unauthenticated mail from the manager and forwarding it to Sendgrid smtp service by using valid credentials. It's also possible to use a local mail server or any other smtp service online.


```
  postfix:
    image: eeacms/postfix:2.10-3.5
    hostname: wazuh-smtp
    restart: always
    environment:
      - MTP_RELAY=smtp.sendgrid.net
      - MTP_PORT=587
      - MTP_USER=apikey
      - MTP_PASS=secret-key
      - MTP_HOST=mailer.example.com
```
