### ISSUE TITLE
Elasticsearch LDAP integration

### ISSUE THREAD

**Issue by arunasp** [wazuh/wazuh-docker#245]
Hello team,

The current authentication to Kibana is provided by Nginx which is not good enough authenticating multiple users in organisation. The Elasticsearch have functionality with Xpack plugin for users authentication in LDAP servers. This feature is available on free/basic license. After implementation this feature it would add second factor authentication inside of Kibana after implementation in Docker startup scripts.

Then startup scripts should check if Xpack is enabled and set up Kibana+Elasticsearch+Filebeat in Wazuh.

The following configuration can be used for integration in elasticsearch.yml - https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-ldap-realm.html:

```yaml
xpack.security.enabled: ${XPACK_ENABLED}
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: config/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: config/elastic-certificates.p12
xpack:
  security:
    authc:
      realms:
        ldap:
          ldap1:
            order: 0
            url: "${LDAP_URL}"
            bind_dn: "${LDAP_BIND_DN}"
            user_search:
              base_dn: "${LDAP_UID_BASE_DN}"
              filter: "${LDAP_FILTER:(cn={0})}"
            group_search:
              base_dn: "${LDAP_GID_BASE_DN}"
            files:
              role_mapping: "/usr/share/elasticsearch/config/role_mapping.yml"
            unmapped_groups_as_roles: false
```
The role_mapping.yml:
```yaml
admin:
 - "CN=${LDAP_ADMIN_BIND_DN}"
users:
 - "CN=${LDAP_USERS_BIND_DN}"
```
The ES setup:
```shell
    curl -uelastic:${ELASTIC_PW} -XPUT -H 'Content-Type: application/json' "http://localhost:9200/_xpack/security/user/kibana/_password" -d '{"password":"'"${KIBANA_PW}"'"}'
    curl -uelastic:${ELASTIC_PW} -XPUT -H 'Content-Type: application/json' "http://localhost:9200/_xpack/security/user/wazuh/_password" -d '{"password":"'"${WAZUH_PW}"'"}'
    curl -XPUT -uelastic:${ELASTIC_PW} 'http://localhost:9200/_license' -H "Content-Type: application/json" -d @/usr/share/elasticsearch/config/license.json
```

Hopefully that can be implemented soon as authentication is one of critical security components.

Cheers!
