### ISSUE TITLE
Define service integration on Wazuh image

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#277]
### Service integration

On this issue we'll define how many services will run on the Wazuh Docker image.

The idea is to define a deployment methodology good enough for both simple and complex scenarios.

##### All-in-one

- Manager + API + Filebeat + Postfix

The current image bundles the Wazuh manager, API, Filebeat and Postfix all in the same container. We're looking into readjust these to follow the Docker philosophy as much as possible without jeopardizing user experience.

##### Independent Filebeat
- Manager + API  + Postfix
- Filebeat

Moving Filebeat to a separate container could be a good starting point. This will require both containers to share a common volume for filebeat to read the `alerts.log` file.

##### Independet Filebeat and Postfix
- Manager + API
- Postfix
- Filebeat

An improvement on the previous method could be moving the Postfix relay also to a separate container.

**Comment by xr09** [comment]
#### Filebeat

To move filebeat out of the main container we can use the official image from Elastic. 

- [docker.elastic.co/beats/filebeat](https://www.docker.elastic.co/)

Both containers will share a common volume with the file `alerts.json`, this will be mounted as `rw` for the manager and `ro` for filebeat.

#### SMTP Relay

Wazuh expects an SMTP relay in the config, usually on a VM you can install it on the same host as it's stated on the docs, but in a container environment an individual service is the way to go.

We'll use this docker image as the recommended for SMTP relay but users can pick their own as well.

- https://hub.docker.com/r/eeacms/postfix

The role of a SMTP relay is to forward the mail notifications from Wazuh to a valid mail server, in this example we're accepting unauthenticated mail from the manager and forwarding it to Sendgrid smtp service by using valid credentials. It's also possible to to use a local mail server or any other smtp service online.


```
  postfix:
    image: eeacms/postfix:2.10-3.5
    hostname: wazuh-smtp
    restart: always
    environment:
      - MTP_RELAY=smtp.sendgrid.net
      - MTP_PORT=587
      - MTP_USER=apikey
      - MTP_PASS=secret-key
      - MTP_HOST=mailer.example.com
```
