### ISSUE TITLE
cross cluster searching

### ISSUE THREAD

**Issue by RANGERBEE** [wazuh/wazuh-docker#32]
Hello Guys,

  Could you recommend a setting for enabling cross cluster searching.  I have tried the following with no joy.

Thank you!

in docker-compose.yml

```yml
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=wazuh_node-1
      - cluster.name=w-docker-cluster
      - network.host=0.0.0.0
#      - discovery.zen.ping.unicast.hosts=10.0.1.194
#      - discovery.zen.minimum_master_nodes=2
#      - node.master=true
#      - node.data=true
#      - discovery.zen.ping_timeout=10s
      - search.remote.cluster_one=10.0.1.194
      - search.remote.cluster_one.skip_unavailable=true
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
#    volumes:
#      - my-path:/usr/share/elasticsearch/data
    networks:
        - docker_elk
```
