### ISSUE TITLE
Kibana Error on Plugin install

### ISSUE THREAD

**Issue by FloThinksPi** [wazuh/wazuh-docker#34]
Kibana can not install the Wazuh plugin because of mailformed URL

```
kibana_1         | Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.2.zip/https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.2.zip-6.1.2.zip
kibana_1         | Plugin installation was unsuccessful due to error "No valid url specified."
```

The value WAZUH_KIBANA_PLUGIN_URL gets incorrectly parsed and clamped between 2 other urls

**Comment by jlruizmlg** [comment]
HI, @FloThinksPi I just try it and seems like works for me, can you share your docker-compose.yml? Or you are using the default one.

```
o":0,"_primary_term":1}Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.2.zip
kibana_1         | Transferring 4580274 bytes....................
kibana_1         | Transfer complete
kibana_1         | Retrieving metadata from plugin archive
kibana_1         | Extracting plugin archive
kibana_1         | Extraction complete
kibana_1         | Optimizing and caching browser bundles...
```

**Comment by RANGERBEE** [comment]
This is my compose file:
```yml
version: '2'

services:
  wazuh:
    image: wazuh/wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    networks:
        - docker_elk
    volumes:
      - ./wazuh/ruleset/.:/var/ossec/data/ruleset:Z
#      - my-path:/etc/postfix:Z
    depends_on:
      - elasticsearch
  logstash:
    image: wazuh/wazuh-logstash
    hostname: logstash
    restart: always
    command: -f /etc/logstash/conf.d/
#    volumes:
#      - my-path:/etc/logstash/conf.d:Z
    links:
     - kibana
     - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
      - XPACK_MONITORING_ENABLED=false
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=ossec-node-1
      - network.host=0.0.0.0
      - cluster.name=docker-cluster
      - network.publish_host=10.0.1.199
      - discovery.zen.ping.unicast.hosts=10.0.1.194:9300, 10.0.1.199:9300
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
#    volumes:
#      - my-path:/usr/share/elasticsearch/data:Z
    networks:
        - docker_elk
  kibana:
    image: wazuh/wazuh-kibana
    hostname: kibana
    restart: always
#    ports:
#      - "5601:5601"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh
    entrypoint: /wait-for-it.sh elasticsearch
#    environment:
#      - http_proxy=yourproxy
#      - https_proxy=yourproxy
#      - "WAZUH_KIBANA_PLUGIN_URL=http://your.repo/wazuhapp-3.1.0-6.1.2.zip"
  nginx:
    image: wazuh/wazuh-nginx
    hostname: nginx
    restart: always
    entrypoint: /run.sh
    environment:
      - NGINX_PORT=443
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - my-path:/etc/nginx/conf.d:Z
    networks:
      - docker_elk
    depends_on:
      - kibana
    links:
      - kibana

networks:
  docker_elk:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
```
These are my errors:  (app in Kibana no longer opens when connected successfully to cluster)

```console
2/7/2018 8:09:10 PM{"acknowledged":true}{"acknowledged":true}{"error":{"root_cause":[{"type":"unavailable_shards_exception","reason":"[wazuh-alerts-3.x-2018.02.07][1] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[wazuh-alerts-3.x-2018.02.07][1]] containing [index {[wazuh-alerts-3.x-2018.02.07][wazuh][sample], source[{  \"@timestamp\": \"2015-03-18T15:55:55.000Z\",  \"AlertsFile\": \"sample\",  \"full_log\": \"sample\",  \"location\": \"sample\",  \"GeoLocation\": {    \"country_name\": \"sample\",    \"location\": [0.0,0.0]  },  \"agent\": {    \"name\": \"sample\"  },  \"data\": {    \"title\": \"sample\",    \"protocol\": \"sample\",    \"action\": \"sample\",    \"srcip\": \"sample\",    \"dstip\": \"sample\",    \"srcport\": \"sample\",    \"dstport\": \"sample\",    \"srcuser\": \"sample\",    \"dstuser\": \"sample\",    \"id\": \"sample\",    \"status\": \"sample\",    \"data\": \"sample\",    \"system_name\": \"sample\",    \"url\": \"sample\",\t\"audit\": {      \"command\": \"sample\",      \"type\": \"sample\",      \"egid\": \"sample\",      \"euid\": \"sample\",      \"exe\": \"sample\",      \"gid\": \"sample\",      \"uid\": \"sample\",      \"directory\": {        \"name\": \"sample\"      },      \"file\": {        \"mode\": \"sample\",        \"name\": \"sample\"      }\t},\t\"oscap\": {      \"check\": {        \"result\": \"sample\",        \"severity\": \"sample\",        \"title\": \"sample\"      },      \"scan\": {        \"id\": \"sample\",        \"content\": \"sample\",        \"score\": 1.55,        \"profile\": {          \"title\": \"sample\"        }      }    }  },  \"rule\": {    \"cis\": [\"sample\"],    \"description\": \"sample\",    \"groups\": [\"sample\"],    \"id\": \"sample\",    \"level\": 0,    \"pci_dss\": [\"sample\"]  },  \"syscheck\": {    \"gname_after\": \"sample\",    \"gname_before\": \"sample\",    \"guid_after\": \"sample\",    \"guid_before\": \"sample\",    \"md5_after\": \"sample\",    \"md5_before\": \"sample\",    \"path\": \"sample\",    \"perm_after\": \"sample\",    \"perm_before\": \"sample\",    \"uid_after\": \"sample\",    \"uid_before\": \"sample\",    \"uname_after\": \"sample\",    \"uname_before\": \"sample\",    \"event\": \"sample\"  }}]}]]"}],"type":"unavailable_shards_exception","reason":"[wazuh-alerts-3.x-2018.02.07][1] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[wazuh-alerts-3.x-2018.02.07][1]] containing [index {[wazuh-alerts-3.x-2018.02.07][wazuh][sample], source[{  \"@timestamp\": \"2015-03-18T15:55:55.000Z\",  \"AlertsFile\": \"sample\",  \"full_log\": \"sample\",  \"location\": \"sample\",  \"GeoLocation\": {    \"country_name\": \"sample\",    \"location\": [0.0,0.0]  },  \"agent\": {    \"name\": \"sample\"  },  \"data\": {    \"title\": \"sample\",    \"protocol\": \"sample\",    \"action\": \"sample\",    \"srcip\": \"sample\",    \"dstip\": \"sample\",    \"srcport\": \"sample\",    \"dstport\": \"sample\",    \"srcuser\": \"sample\",    \"dstuser\": \"sample\",    \"id\": \"sample\",    \"status\": \"sample\",    \"data\": \"sample\",    \"system_name\": \"sample\",    \"url\": \"sample\",\t\"audit\": {      \"command\": \"sample\",      \"type\": \"sample\",      \"egid\": \"sample\",      \"euid\": \"sample\",      \"exe\": \"sample\",      \"gid\": \"sample\",      \"uid\": \"sample\",      \"directory\": {        \"name\": \"sample\"      },      \"file\": {        \"mode\": \"sample\",        \"name\": \"sample\"      }\t},\t\"oscap\": {      \"check\": {        \"result\": \"sample\",        \"severity\": \"sample\",        \"title\": \"sample\"      },      \"scan\": {        \"id\": \"sample\",        \"content\": \"sample\",        \"score\": 1.55,        \"profile\": {          \"title\": \"sample\"        }      }    }  },  \"rule\": {    \"cis\": [\"sample\"],    \"description\": \"sample\",    \"groups\": [\"sample\"],    \"id\": \"sample\",    \"level\": 0,    \"pci_dss\": [\"sample\"]  },  \"syscheck\": {    \"gname_after\": \"sample\",    \"gname_before\": \"sample\",    \"guid_after\": \"sample\",    \"guid_before\": \"sample\",    \"md5_after\": \"sample\",    \"md5_before\": \"sample\",    \"path\": \"sample\",    \"perm_after\": \"sample\",    \"perm_before\": \"sample\",    \"uid_after\": \"sample\",    \"uid_before\": \"sample\",    \"uname_after\": \"sample\",    \"uname_before\": \"sample\",    \"event\": \"sample\"  }}]}]]"},"status":503}Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.1.zip
2/7/2018 8:09:10 PMTransferring 4585190 bytes....................
2/7/2018 8:09:10 PMTransfer complete
2/7/2018 8:09:10 PMRetrieving metadata from plugin archive
2/7/2018 8:09:10 PMExtracting plugin archive
2/7/2018 8:09:13 PMExtraction complete
2/7/2018 8:09:13 PMOptimizing and caching browser bundles...
2/7/2018 8:20:18 PMPlugin installation complete
2/7/2018 8:20:48 PMSetting API credentials into Wazuh APP
2/7/2018 8:20:48 PMWazuh APP already configured
2/7/2018 8:21:04 PM{"type":"log","@timestamp":"2018-02-07T20:21:04Z","tags":["status","plugin:xpack_main@6.1.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Red","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
2/7/2018 8:21:04 PM{"type":"log","@timestamp":"2018-02-07T20:21:04Z","tags":["status","plugin:searchprofiler@6.1.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Red","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
2/7/2018 8:21:04 PM{"type":"log","@timestamp":"2018-02-07T20:21:04Z","tags":["status","plugin:tilemap@6.1.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Red","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
2/7/2018 8:21:04 PM{"type":"log","@timestamp":"2018-02-07T20:21:04Z","tags":["status","plugin:watcher@6.1.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Red","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
2/7/2018 8:21:04 PM{"type":"log","@timestamp":"2018-02-07T20:21:04Z","tags":["status","plugin:logstash@6.1.1","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Red","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
2/7/2018 8:21:04 PM{"type":"log","@timestamp":"2018-02-07T20:21:04Z","tags":["listening","info"],"pid":1,"message":"Server running at http://0.0.0.0:5601"}
2/7/2018 8:21:04 PM{"type":"log","@timestamp":"2018-02-07T20:21:04Z","tags":["\u001b[34mwazuh\u001b[39m","initialize","error"],"pid":1,"message":"Error creating index-pattern."}
```
