### ISSUE TITLE
agentless solaris lost when restart

### ISSUE THREAD

**Issue by mserranolm** [wazuh/wazuh-docker#344]
When I apply the command to add 2 servers through the agentless system in docker at the time of rebooting I always lose the added hosts, how can I make it persistent?

**Comment by xr09** [comment]
Hello @mserranolm, you've just found a bug in our Docker image, currently it's not saving state for the agentless hosts, this is a corner case we were not testing before.

I've created the issue #349 to address this ASAP, already working on a fix.

Thanks a ton for reporting this!

**Comment by xr09** [comment]
A temporary solution could be saving the agentless directory on a volume, like this:
```yml
services:
  wazuh:
    image: wazuh/wazuh:3.12.3_7.6.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - agentless:/var/ossec/agentless


volumes:
  agentless:
```

Mind you should save the file `/var/ossec/agentless/.passlist` from that volume before upgrading to the next version we will release with the fix.
