### ISSUE TITLE
how in docker change the user foo

### ISSUE THREAD

**Issue by mserranolm** [wazuh/wazuh-docker#345]
I can not find documentation how can I change the user foo that is standard since it is not safe for our administration

**Comment by xr09** [comment]
Hi @mserranolm,

You can use the environment variables **API_USER** and **API_PASS**.

Something like this on your docker-compose, or you might prefer a `.env` file:

```yml
services:
  wazuh:
    image: wazuh/wazuh:3.12.3_7.6.2
    hostname: wazuh-manager
    .....
    environment:
      - API_USER=frodo
      - API_PASS=baggins
```

I'm marking this issue as solved, feel free to repoen if need clarification.
