### ISSUE TITLE
logstash.conf read error?

### ISSUE THREAD

**Issue by RANGERBEE** [wazuh/wazuh-docker#37]
hello,

  I have edited the logstash.conf file and tried to mount the host folder with error.
```console
[2018-02-14T19:10:59,969][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/etc/logstash/conf.d/*"}
```
My config in docker-compose file for logstash service:
```yml
 logstash:
    image: wazuh/wazuh-logstash
    hostname: logstash
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config/.:/etc/logstash/conf.d:Z
    links:
     - kibana
     - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
      - XPACK_MONITORING_ENABLED=false
```

My config in logstash/Dockerfile:
```yml
FROM docker.elastic.co/logstash/logstash:6.1.3
USER root
COPY ./config/logstash.conf /etc/logstash/conf.d/logstash.conf
RUN chown 1000:1000 /etc/logstash/conf.d
RUN chmod 755 /etc/logstash/conf.d
```
Could you all tell me what I may be missing?

Thanks!
