### ISSUE TITLE
Test upgrade scenario from 3.13 to 4.0

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#381]
This issue will document an upgrade scenario from 3.13 to 4.0

- [x] Deploy a new cluster using `v3.13.1_7.8.0`
- [x] Add agents to the cluster, regular and agentless. Generate sample data.
- [x] Migrate data from single old volume to all the new volumes
- [x] Deploy new 4.0 cluster using the new volumes
- [x] Test agent's database integrity.
- [x] Test agentless monitoring.

**Comment by xr09** [comment]
Since the 3.13.1 cluster is using unnamed volumes the recommended procedure is to add a new volume and attach it to this container.

To create a new named volume: `docker volume create migration`

Then let's attach it to the current cluster on its docker-compose.yml

```yml
volumes:
  migration:
    external:
      name: migration


services:
  wazuh:
    image: wazuh/wazuh:3.13.1_7.8.0
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - migration:/migration
```

Proceed to rebuild the container with this volume attached: `docker-compose up -d`

Now copy the content of `/var/ossec/data` to `/migration` on your Wazuh container:  

`docker exec wazuh-docker_wazuh_1 cp -rv /var/ossec/data /migration`

You can stop the cluster now: `docker-compose stop`

The relevant data from your Wazuh container lies in the `migration` volume, feel free to inspect it:

`docker run --rm -v migration:/migration alpine:latest ls -l /migration/data`

Now  let's mount the volume to the new 4.0 cluster:

```yaml
services:
  wazuh:
  ...
    volumes:
      ...
      - migration:/migration


volumes:
  ...
  migration:
    external:
      name: migration
```

Re-build the container with `docker-compose up -d` and now the `migration` volume is mounted on the Wazuh container at `/migration`.
