### ISSUE TITLE
Kibana Dashboard, and Active Responses log file

### ISSUE THREAD

**Issue by Davincible** [wazuh/wazuh-docker#384]
Hi, 

Everytime I restart my server, all files are lost. So I already shared the volume for the settings, as in the documentation. However, I also made custom kibana discover dashboards, but now these are lost after reboot. Which folder are they stored in? so I can share them too with the host.

Also, after sharing the ossec folder, my agent is no longer reading the active responses log as described [here](https://wazuh.com/blog/blocking-attacks-active-response/), I made those setting changes, but they have no effect. How can I fix that?

**Comment by xr09** [comment]
Hello @Davincible,

Kibana saves its objects on Elasticsearch's `.kibana` index, you have to save elasticsearch data into a volume.

```yaml
elasticsearch:
  ...
  volumes:
    - elastic-data:/usr/share/elasticsearch/data

volumes:
  elastic-data:
```

Regarding your second question, what do you mean by sharing the ossec folder? Like in a Windows network share?

**Comment by Davincible** [comment]
Thanks I'll try that.
I mean that I shared my ossec folder the same way you described above, in the docker compose file

**Comment by xr09** [comment]
Could you share the `wazuh` service definition from your `docker-compose.yml`?

**Comment by Davincible** [comment]
@xr09 

```
# Wazuh App Copyright (C) 2020 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.12.2_7.6.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - /opt/WazuhDocker/data/:/var/ossec/data/:Z

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.12.2_7.6.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    image: wazuh/wazuh-kibana:3.12.2_7.6.2
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
    ports:
      - "5601:5601"

        #  nginx:
          #    image: wazuh/wazuh-nginx:3.12.2_7.6.2
    #    hostname: nginx
    #    restart: always
    #    environment:
            #      - NGINX_PORT=443
        #      - NGINX_CREDENTIALS
        #    ports:
        #        #      - "80:80"
        #        #      - "443:443"
        #    depends_on:
            #      - kibana
        #    links:
            #      - kibana:kibana
```

**Comment by xr09** [comment]
I see, you're sharing the folder directly but that may cause file owner/permission issues, use named volumes instead.

This way you create two named volumes and assign these to the containers:

```yaml
volumes:
  wazuh-data:
  elastic-data:

services:
  wazuh:
    image: wazuh/wazuh:3.12.2_7.6.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - wazuh-data:/var/ossec/data

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.12.2_7.6.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:                                                                                                   ## This is new
        - elastic-data:/usr/share/elasticsearch/data
```

This will be the recommended procedure starting with the next version.
