### ISSUE TITLE
external filebeat container - mount to "volumes_from"

### ISSUE THREAD

**Issue by RANGERBEE** [wazuh/wazuh-docker#39]
Could you help - I am trying to mount volume in wazuh manager - alerts to host. This is so that the filebeat container can tail the alerts file and send out to another logstash.

Please let me know if you see a problem with my compose file.

```yml
version: '2'

services:
  wazuh:
    image: wazuh/wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    networks:
        - docker_elk
    volumes:
      - ./wazuh/ruleset:/var/ossec/data/ruleset:Z
      - alerts:/var/ossec/data/logs/alerts:Z
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
    depends_on:
    - ossec:ro
    hostname: filebeat
    networks:
      - docker_elk
    restart: always
    volumes_from:
    - wazuh:ro
    depends_on:
    - wazuh

  logstash:
    image: wazuh/wazuh-logstash
    hostname: logstash
    restart: always
    command: -f /etc/logstash/conf.d
#    volumes:
#      - ./logstash/config/.:/etc/logstash/conf.d
    links:
     - kibana
     - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
      - XPACK_MONITORING_ENABLED=false

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
#    volumes:
#      - my-path:/usr/share/elasticsearch/data:Z
    networks:
        - docker_elk

  kibana:
    image: wazuh/wazuh-kibana
    hostname: kibana
    restart: always
#    ports:
#      - "5601:5601"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh
    entrypoint: /wait-for-it.sh elasticsearch
    environment:
      - "NODE_OPTIONS=--max-old-space-size=3072"
  nginx:
    image: wazuh/wazuh-nginx
    hostname: nginx
    restart: always
    entrypoint: /run.sh
    environment:
      - NGINX_PORT=443
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - my-path:/etc/nginx/conf.d:Z
    networks:
      - docker_elk
    depends_on:
      - kibana
    links:
      - kibana

volumes:
  alerts:
      

networks:
  docker_elk:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

```
