### ISSUE TITLE
Create images compatible with Elasticsearch (xpack)

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#398]
Ealsticsearch (xpack) images are required to provide a direct upgrade path for users without intention of migration to OpenDistro images.

### Tasks

- [x] Create `wazuh` image with v4.0 compatible with old image
- [x] Create `wazuh-kibana` image with a wazuh app compatible with xpack

**Comment by xr09** [comment]
The `wazuh` image was done by adding a new ARG `FILEBEAT_CHANNEL` to the Dockerfile with a default value of `filebeat-oss`, to build an xpack variant this ARG should be set to `filebeat`:

```yaml
wazuh:
build:
  context: wazuh-odfe/
  args:
    - FILEBEAT_CHANNEL=filebeat
image: wazuh/wazuh:4.0.1_7.9.1
```

**Comment by xr09** [comment]
Both images (wazuh and kibana xpack compatible) were tested locally, still pending to test the upgrade use-case.

The kibana Dockerfile was optimized to avoid rebuilding when the entrypoint was modified.

**Comment by priamai** [comment]
Hi there,
I can't wait for this to be completed!
Ideally would love to see another docker-compose file with the ES and Kibana original versions.
Cheers.

**Comment by xr09** [comment]
Hi @priamai , that's the idea, check out [xpack-compose.yml](https://github.com/wazuh/wazuh-docker/blob/e8a12826ccc14cea28b5dbec56af2fc6bf07ab19/xpack-compose.yml) on the PR. 

Still some more testing is required but the images are pretty much ready.

**Comment by xr09** [comment]
### Wazuh 4.0.4 cluster with Elasticsearch-xpack (basic license)

Images were tested with the workflow described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls-docker.html) using a single node Elasticsearch cluster with Kibana and a manager.

![Screenshot_20210202_191557](https://user-images.githubusercontent.com/1380243/106644214-190bdf00-658b-11eb-93d5-f60ec4b8eff8.png)


There were still some pending details on the curl checks since initially the images asumed plain http was being used. Patches are on the PR already.

Next step is launching a multi-node Elasticsearch cluster and documenting the process on the repository.

**Comment by priamai** [comment]
@xr09 could you drive me through the testing.
This is what I have done:

```
git clone https://github.com/wazuh/wazuh-docker.git
wget https://raw.githubusercontent.com/wazuh/wazuh-docker/e8a12826ccc14cea28b5dbec56af2fc6bf07ab19/xpack-compose.yml
paolo@ubuntu02:~/wazuh-docker$ docker-compose -f xpack-compose.yml up -d
```

**ERROR: build path /home/paolo/wazuh-docker/kibana either does not exist, is not accessible, or is not a valid URL.**

I am guessing you have a dockerfile specific for kibana?
where can I pull that from?

**Comment by xr09** [comment]
Hi @priamai, I'm using patched images from the branch `feature-xpack-4.0`.

I'm generating the certs following the steps described on the link from my previous comment.

The xpack-compose.xml I have locally is this one:

```yaml
version: '3.7'

services:
  wazuh:
    build:
      context: wazuh-odfe/
      args:
        - FILEBEAT_CHANNEL=filebeat
        - FILEBEAT_VERSION=7.9.3
    image: wazuh/wazuh:4.0.4_7.9.3_dev
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=none
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/ca.crt
      - SSL_CERTIFICATE=/etc/ssl/wazuh.crt
      - SSL_KEY=/etc/ssl/wazuh.key
    volumes:
      - ossec_api_configuration:/var/ossec/api/configuration
      - ossec_etc:/var/ossec/etc
      - ossec_logs:/var/ossec/logs
      - ossec_queue:/var/ossec/queue
      - ossec_var_multigroups:/var/ossec/var/multigroups
      - ossec_integrations:/var/ossec/integrations
      - ossec_active_response:/var/ossec/active-response/bin
      - ossec_agentless:/var/ossec/agentless
      - ossec_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./xpack/ca/ca.crt:/etc/ssl/ca.crt
      - ./xpack/wazuh/wazuh.crt:/etc/ssl/wazuh.crt
      - ./xpack/wazuh/wazuh.key:/etc/ssl/wazuh.key


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=wazuh-cluster
      - node.name=elasticsearch
      - ELASTIC_PASSWORD=SecretPassword
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certificates/elasticsearch/elasticsearch.key
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certificates/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certificates/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certificates/elasticsearch/elasticsearch.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./xpack/:/usr/share/elasticsearch/config/certificates/

  kibana:
    build: kibana/
    image: wazuh/wazuh-kibana:4.0.4_7.9.3_dev
    hostname: kibana
    restart: always
    ports:
      - 443:5601
    environment:
      - SERVERNAME=localhost
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=SecretPassword
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certificates/ca/ca.crt
      - SERVER_SSL_ENABLED=true
      - XPACK_SECURITY_ENABLED=true
      - SERVER_SSL_KEY=/usr/share/kibana/config/certificates/kibana/kibana.key
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certificates/kibana/kibana.crt
    volumes:
      - ./xpack/:/usr/share/kibana/config/certificates/
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

volumes:
  ossec_api_configuration:
  ossec_etc:
  ossec_logs:
  ossec_queue:
  ossec_var_multigroups:
  ossec_integrations:
  ossec_active_response:
  ossec_agentless:
  ossec_wodles:
  filebeat_etc:
  filebeat_var:
```

**Comment by priamai** [comment]
@xr09 ehy you are totally right, I have pulled the branch and building it right now.

**Comment by xr09** [comment]
## Test with xpack cluster (3 nodes)

Latest update on branch `feature-xpack-4.0` has a working cluster with elasticsearch-xpack (basic license).

For generating the certs the file at `xpack/instances.yml` must be customized:

```yaml
instances:
  - name: elasticsearch
    dns:
      - elasticsearch
      - localhost
    ip:
      - 127.0.0.1

  - name: elasticsearch2
    dns:
      - elasticsearch2
      - localhost
    ip:
      - 127.0.0.1

  - name: elasticsearch3
    dns:
      - elasticsearch3
      - localhost
    ip:
      - 127.0.0.1

  - name: kibana
    dns:
      - kibana
      - localhost
    ip:
      - 127.0.0.1

  - name: wazuh
    dns:
      - wazuh
      - localhost
    ip:
      - 127.0.0.1
```

And then the certs are generated with: `docker-compose -f generate-elasticsearch-certs.yml run --rm generator`

```
xpack
├── bundle.zip
├── ca
│   ├── ca.crt
│   └── ca.key
├── elasticsearch
│   ├── elasticsearch.crt
│   └── elasticsearch.key
├── elasticsearch2
│   ├── elasticsearch2.crt
│   └── elasticsearch2.key
├── elasticsearch3
│   ├── elasticsearch3.crt
│   └── elasticsearch3.key
├── instances.yml
├── kibana
│   ├── kibana.crt
│   └── kibana.key
└── wazuh
    ├── wazuh.crt
    └── wazuh.key
```

Finally by launching the `xpack-compose.yml` the cluster will launch.
