### ISSUE TITLE
Add filebeat as volume

### ISSUE THREAD

**Issue by jlruizmlg** [wazuh/wazuh-docker#40]
In order to do changes in ```filebeat.yml``` easily we can add filebeat folder as mount folder and let ```docker-compose.yml``` mount the folder through the volumes volumes section.

**Comment by RANGERBEE** [comment]
what is correct syntax for multiple logstash hosts?  the load balancing switch is confusing me.

I have this as my filebeat.yml currently - not sure it is correct:

```yml
filebeat:
 prospectors:
  - input_type: log
    paths:
     - "/var/ossec/data/logs/alerts/alerts.json"
    document_type: wazuh-alerts
    json.message_key: log
    json.keys_under_root: true
    json.overwrite_keys: true

output:
 logstash:
   # The Logstash hosts
   hosts: ["logstash:5000", "10.0.1.194:5514"]
#   ssl:
#     certificate_authorities: ["/etc/filebeat/logstash.crt"]

```
