### ISSUE TITLE
Wazzuh not showing docker info

### ISSUE THREAD

**Issue by RRadziejewski** [wazuh/wazuh-docker#410]
Hello I'm using wazzuh 3.9

Agent host: Centos8.2

My problem is that after enabling docker-listener woodle it does not show anything in the ui, am i missing something ?

<img width="829" alt="chrome_2020-11-25_13-42-04" src="https://user-images.githubusercontent.com/32438378/100229453-89133e80-2f24-11eb-9bcd-15b812f6bde4.png">
<img width="389" alt="chrome_2020-11-25_13-42-46" src="https://user-images.githubusercontent.com/32438378/100229457-8add0200-2f24-11eb-8f46-e905b6bb31d5.png">
<img width="835" alt="chrome_2020-11-25_13-43-27" src="https://user-images.githubusercontent.com/32438378/100229466-8ca6c580-2f24-11eb-935a-dcb1d05de979.png">

Thanks in advance for help !!

**Comment by xr09** [comment]
Hello, are you using our Docker images or is it a regular installation with packages?

With our Docker images you need to enable the Docker extension for the Kibana container via env var: 

```yaml
  kibana:
    image: wazuh/wazuh-kibana:version
    hostname: kibana
    environment:
      - EXTENSIONS_DOCKER=true
```
