### ISSUE TITLE
send mail Wazuh Docker

### ISSUE THREAD

**Issue by mserranolm** [wazuh/wazuh-docker#420]
I can not configure for my installation in docker send notification mail, what is the process to activate this feature?

**Comment by xr09** [comment]
Hey there @mserranolm,

Wazuh expects an SMTP relay in the config, usually on a VM you can install it on the same host (as it's stated on the docs), but in a container environment an individual service is recommended.

You may use this docker image for SMTP relay: 

- https://hub.docker.com/r/eeacms/postfix

The role of a SMTP relay is to forward the mail notifications from Wazuh to a valid mail server, in this example we're accepting unauthenticated mail from the manager and forwarding it to Sendgrid smtp service by using valid credentials. It's also possible to to use a local mail server or any other smtp service online.

```
  postfix:
    image: eeacms/postfix:2.10-3.6
    hostname: wazuh-smtp
    restart: always
    environment:
      - MTP_RELAY=smtp.sendgrid.net
      - MTP_PORT=587
      - MTP_USER=apikey
      - MTP_PASS=secret-key
      - MTP_HOST=mailer.example.com
```
