### ISSUE TITLE
Unique node_name for wazuh-worker container

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-docker#433]
Providing a unique name for the wazuh-worker `<node_name>` in the configuration file would allow an arbitrary number of nodes to be created with docker-compose's `--scale` option.
For example by modifying the ossec.conf file with the commands:
```
id=$(hostname -i | tr -d ";.";)
sed 's/<node_name>.*<\/node_name>/<node_name>WAZUH_WORKER-'${id}'<\/node_name>/g' $DIRECTORY/etc/ossec.conf  -i
```
Would append the node's IP to the node_name (without periods) and make it unique.
Allowing the user to specify the number of nodes with the command:
```
docker-compose -f production-cluster.yml up --scale wazuh-worker=3
```

In previous releases, for example 3.9.3_7.2.0 which is featured in [this blogpost](https://wazuh.com/blog/auto-scalable-wazuh-cluster-with-docker-compose/) this would be possible thanks to the use of `/entrypoints-scripts/` which is no longer available.

**Comment by xr09** [comment]
Those `entrypoint-scripts` were removed when switching to the new images based on s6-overlay. An equivalent solution will be provided to guarantee unique names on the workers.

**Comment by xr09** [comment]
Entrypoints script are being re-enabled, but due to the changes on our persistency model now when scaled all the workers share the same volumes, and the Wazuh processes start crashing due to shared state.

![Screenshot_20210203_130531](https://user-images.githubusercontent.com/1380243/106744797-83bb2a00-6620-11eb-9c59-032a8f99d5ab.png)


Tried disabling the volumes like this:

```yaml
  wazuh-worker:
    image: wazuh/wazuh-odfe:4.0.4_1.11.0_dev
    build: wazuh-odfe/
    hostname: wazuh-worker
    restart: always
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    volumes:
      # - worker-ossec-api-configuration:/var/ossec/api/configuration
      # - worker-ossec-etc:/var/ossec/etc
      # - worker-ossec-logs:/var/ossec/logs
      # - worker-ossec-queue:/var/ossec/queue
      # - worker-ossec-var-multigroups:/var/ossec/var/multigroups
      # - worker-ossec-integrations:/var/ossec/integrations
      # - worker-ossec-active-response:/var/ossec/active-response/bin
      # - worker-ossec-agentless:/var/ossec/agentless
      # - worker-ossec-wodles:/var/ossec/wodles
      # - worker-filebeat-etc:/etc/filebeat
      # - worker-filebeat-var:/var/lib/filebeat
      - ./production_cluster/ssl_certs/root-ca.pem:/etc/ssl/root-ca.pem
      - ./production_cluster/ssl_certs/filebeat.pem:/etc/ssl/filebeat.pem
      - ./production_cluster/ssl_certs/filebeat.key:/etc/ssl/filebeat.key
      - ./production_cluster/wazuh_cluster/wazuh_worker.conf:/wazuh-config-mount/etc/ossec.conf
      - ./scale/worker.sh:/entrypoint-scripts/worker.sh
```

And the cluster scales up correctly, but state is not being saved to volumes.

![Screenshot_20210203_130222](https://user-images.githubusercontent.com/1380243/106744564-376fea00-6620-11eb-81a3-14621ea056a8.png)

This use case covers dynamically scaling of the workers, the same can be done manually by adding another worker definition on the compose file, with its own volumes. Or another more fitting solution would be Kubernetes.


### Scale scripts
master.sh
```bash
#!/bin/bash

DIRECTORY="/var/ossec"

start_config="$(grep -n "<cluster>" ${DIRECTORY}/etc/ossec.conf | cut -d':' -f 1)"
end_config="$(grep -n "</cluster>" ${DIRECTORY}/etc/ossec.conf | cut -d':' -f 1)"

# remove previous configuration
sed -i "${start_config},${end_config}d" ${DIRECTORY}/etc/ossec.conf

# use any source for registration process
sed -i "s/<use_source_ip>yes/<use_source_ip>no/g" ${DIRECTORY}/etc/ossec.conf

cat >> ${DIRECTORY}/etc/ossec.conf <<- EOM
<ossec_config>
  <cluster>
    <name>wazuh</name>
    <node_name>wazuh-master</node_name>
    <node_type>master</node_type>
    <key>c98b62a9b6169ac5f67dae55ae4a9088</key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>wazuh-master</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>
  </cluster>
 </ossec_config>

EOM
```

worker.sh
```bash
#!/bin/bash

DIRECTORY="/var/ossec"

id=$(hostname -i | tr -d ";.")

start_config="$(grep -n "<cluster>" ${DIRECTORY}/etc/ossec.conf | cut -d':' -f 1)"
end_config="$(grep -n "</cluster>" ${DIRECTORY}/etc/ossec.conf | cut -d':' -f 1)"

# remove previous configuration
sed -i "${start_config},${end_config}d" ${DIRECTORY}/etc/ossec.conf

cat >> ${DIRECTORY}/etc/ossec.conf <<- EOM
 <ossec_config>
   <cluster>
    <name>wazuh</name>
    <node_name>wazuh-worker-${id}</node_name>
    <node_type>worker</node_type>
    <key>c98b62a9b6169ac5f67dae55ae4a9088</key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>wazuh-master</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>
  </cluster>
 </ossec_config>

EOM
```
