### ISSUE TITLE
Add goss binary for healthcheck

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#438]
## Description

To provide a consistent base for health checks we will add the `goss` binary (already used for image validation on the Github Actions PR pipeline).

## Goals

This will make it possible to perform health checks both on Docker and Kubernetes environments:

On docker-compose:

```yaml
  wazuh:
    build:  wazuh-odfe/
    image: wazuh/wazuh-odfe:dev-version
    hostname: wazuh-manager
    restart: unless-stopped
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    ...
    volumes:
      ...
      - ./liveness.yaml:/var/goss/liveness.yaml
    healthcheck:
      test: /usr/local/bin/goss -g /var/goss/liveness.yaml validate
      interval: "20s"
      timeout: "3s"
      start_period: "20s"
      retries: 1
```

On Kubernetes:

```yaml
livenessProbe:
      exec:
        command:
        - /usr/local/bin/goss
        - '-g'
        - '/var/goss/liveness.yaml'
        -  'validate'
      initialDelaySeconds: 20
      periodSeconds: 20
```

`liveness.yaml`

```yaml
port:
  tcp:1544:
    listening: true
    ip:
    - 0.0.0.0
  tcp:1515:
    listening: true
    ip:
    - 0.0.0.0
  tcp:55000:
    listening: true
    ip:
    - 0.0.0.0
process:
  filebeat:
    running: true
  ossec-analysisd:
    running: true
  ossec-authd:
    running: true
  ossec-execd:
    running: true
  ossec-monitord:
    running: true
  ossec-remoted:
    running: true
  ossec-syscheckd:
    running: true
  s6-supervise:
    running: true
  wazuh-db:
    running: true
  wazuh-modulesd:
    running: true
```
