### ISSUE TITLE
I can't figure out how to integrate wazuh agent on container 

### ISSUE THREAD

**Issue by ViralFever** [wazuh/wazuh-docker#440]
I wan to monitor docker container activities using wazuh but I can't make it happen. I tried enabling woodle docker listener on host OS but doesn't work. Please let me if wazuh has visibility inside of container.

**Comment by xr09** [comment]
Hi @ViralFever, we have an ongoing issue to Dockerize the agent, now that you mention the Docker wodle I'll add the requirements to the base container.

In case you have the manager running on the same Docker host that you need to monitorize as stated on the [docs](https://documentation.wazuh.com/4.0/docker-monitor/monitoring_containers_activity.html) we ship all the dependencies on the manager starting with v3.9.0 so you could just share the Docker socket to the manager container:

```yaml
  wazuh:
    image: wazuh/wazuh-odfe:version
    ...
    volumes:
      ...
      - /var/run/docker.sock:/var/run/docker.sock
```

Hope this helps!
