### ISSUE TITLE
wazuh docker install on arm

### ISSUE THREAD

**Issue by vncloudsco** [wazuh/wazuh-docker#532]
i am looking to install wazuh on arm system, but I get an error that can't be installed because I can't install elasticsearch, however i know they are runnable with docker on arm, how can i install wazuh arm platform?
refer: 
https://github.com/gagara/docker-elk-arm64
https://github.com/elastic/kibana/pull/84831
https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/576

**Comment by vncloudsco** [comment]
dear: @vcerenu 

many thank you support me, but 

> For the images that use opendistro you must modify the Dockerfiles of the wazuh-docker/kibana-odfe and wazuh-docker/wazuh-odfe paths.


I don't know the composition of the image, wazuh-docker/kibana-odfe  I want to know what dockerfile here is installed only kibana or also elasticsearch?

> build-from-sources.yml
 
by default elasticsearch already supports ARM can I use its original image instead? because I see in this file it has an image as follows

```
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=wazuh-cluster
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

```

>    image: amazon/opendistro-for-elasticsearch:1.13.2

The problem I have is that this image does not support ARM.
