### ISSUE TITLE
All event data lost on docker-compose down/up

### ISSUE THREAD

**Issue by cysea** [wazuh/wazuh-docker#564]
Hi,

I'm trying to figure out what's going wrong, but it seems that all the data is gone upon recreating the stack.
I still see the raw logs in `/var/lib/docker/volumes/wazuh_ossec_logs/_data/`, but they are not displayed in the web UI.

![image](https://user-images.githubusercontent.com/59068073/147407956-9de2e6c5-a3ec-47c2-82b8-e50d2b8a6c96.png)

![image](https://user-images.githubusercontent.com/59068073/147407855-3eb73cfb-aafe-409c-a3f2-9f5d6daab43c.png)

Before recreating the stack all I modified was `/var/lib/docker/volumes/wazuh_filebeat_etc/_data/filebeat.yml` to include a self-signed cert, and copied the certs to `/var/lib/docker/volumes/wazuh_filebeat_etc/_data/certs/` 

Isn't the agent->node connection encrypted somehow (ports 1514, 1515, 514/udp)? From my understanding filebeat only talks to elasticsearch, and since it's all in a single stack, ssl should be completely optional? Please correct me if wrong. Same question goes for elastic's ssl config? Should be completely optional?

```
root@wazuh-manager filebeat]# cat filebeat.yml

# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false
output.elasticsearch:
  hosts: ['https://elasticsearch:9200']
  username: 'x'
  password: 'x'
  #ssl.verification_mode: none
  ssl.certificate_authorities: /etc/filebeat/certs/rootCA.pem
  ssl.certificate: /etc/filebeat/certs/hq.local.crt
  ssl.key: /etc/filebeat/certs/hq.local.key
```

```
[root@wazuh-manager /]# filebeat test output
elasticsearch: https://elasticsearch:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 10.0.0.91
    dial up... OK
  TLS...
    security... WARN server's certificate chain verification is disabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
```
```
[root@wazuh-manager /]# curl https://elasticsearch:9200/_cat/indices/wazuh-alerts-* -u x:x -k
green open wazuh-alerts-4.x-2021.12.26 NGHLiwpzQH-03g3-2mgfjg 3 0 13 0 73kb 73kb
```

`docker-compose.yml`
```
# Wazuh App Copyright (C) 2021 Wazuh Inc. (License GPLv2)
version: '3.7'

networks:
  wazuh_traefik:
    external: true
  wazuh:
    name: wazuh
    ipam:
      config:
        - subnet: 10.0.0.88/29


services:
  wazuh:
    image: wazuh/wazuh-odfe:4.2.5
    restart: unless-stopped

    container_name: wazuh-manager
    hostname: wazuh-manager

    networks:
      wazuh:
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      #- "55000:55000"

    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTIC_USERNAME=x
      - ELASTIC_PASSWORD=x
      #- FILEBEAT_SSL_VERIFICATION_MODE=none

    volumes:
      - ossec_api_configuration:/var/ossec/api/configuration
      - ossec_etc:/var/ossec/etc
      - ossec_logs:/var/ossec/logs
      - ossec_queue:/var/ossec/queue
      - ossec_var_multigroups:/var/ossec/var/multigroups
      - ossec_integrations:/var/ossec/integrations
      - ossec_active_response:/var/ossec/active-response/bin
      - ossec_agentless:/var/ossec/agentless
      - ossec_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat


  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    restart: unless-stopped

    container_name: elasticsearch
    hostname: elasticsearch

    networks:
      wazuh:

    environment:
      - discovery.type=single-node
      - cluster.name=wazuh-cluster
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true

    volumes:
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./disabledlog4j.options:/etc/elasticsearch/jvm.options.d/disabledlog4j.options

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536


  kibana:
    image: wazuh/wazuh-kibana-odfe:4.2.5
    restart: unless-stopped

    container_name: kibana
    hostname: kibana

    networks:
      wazuh_traefik:
      wazuh:

    environment:
      - ELASTICSEARCH_USERNAME=x
      - ELASTICSEARCH_PASSWORD=x
      - SERVER_SSL_ENABLED=false
      #- SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/opendistroforelasticsearch.example.org.cert
      #- SERVER_SSL_KEY=/usr/share/kibana/config/opendistroforelasticsearch.example.org.key

    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh


volumes:
  ossec_api_configuration:
  ossec_etc:
  ossec_logs:
  ossec_queue:
  ossec_var_multigroups:
  ossec_integrations:
  ossec_active_response:
  ossec_agentless:
  ossec_wodles:
  filebeat_etc:
  filebeat_var:
```

Also, I've noticed this weird username/password config in `/usr/share/kibana/config/kibana.yml`
Should I modify it here or does the kibana container automatically use the env variables from docker-compose.yml?
```
[root@kibana config]# cat kibana.yml
---
# Description:
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.hosts: https://elasticsearch:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

# Use this setting if you are running kibana without https
opendistro_security.cookie.secure: false

newsfeed.enabled: false
telemetry.optIn: false
telemetry.enabled: false
security.showInsecureClusterWarning: false
# To configure a WMS map server for use with Kibana, see:
# https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/maptiles/
map.includeElasticMapsService: false
server.defaultRoute: /app/wazuh?security_tenant=global
```
