### ISSUE TITLE
Cannot create container for service elasticsearch

### ISSUE THREAD

**Issue by marcRBD** [wazuh/wazuh-docker#6]
hello
i'm not familiar with docker, but does the elastic container misses in files ?

wazuh-docker-master# docker-compose up
Creating wazuhdockermaster_elasticsearch_1

ERROR: for elasticsearch  Cannot create container for service elasticsearch: b'invalid port specification: "None"'
ERROR: Encountered errors while bringing up the project.

Thanks

**Comment by jlruizmlg** [comment]
Hi @marcRBD seems like you miss something in the configuration, can you share your docker-compose.yml to take a look?
Thanks!

**Comment by marcRBD** [comment]
hi 

i not change anything:
file
-rw-r--r--  1 root root  1456 mars  31 14:06 docker-compose.yml
drwxr-xr-x  2 root root  4096 mars  31 14:06 images
drwxr-xr-x  3 root root  4096 mars  31 14:06 kibana
drwxr-xr-x  3 root root  4096 mars  31 14:06 logstash
-rw-r--r--  1 root root 17454 mars  31 14:06 README.md
drwxr-xr-x  3 root root  4096 avril  6 13:53 wazuh


[docker-compose.zip](https://github.com/wazuh/wazuh-docker/files/902697/docker-compose.zip)

thanks

**Comment by jlruizmlg** [comment]
@marcRBD do you  have any other service running in the port 9200 or 9300?

Try to use the next docker-compose.yml, the only changes is remove the port section

```
version: '2'

services:
  wazuh:
    image: wazuh/wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514/udp:1514/udp"
      - "1515:1515"
      - "514/udp:514/udp"
      - "55000:55000"
    networks:
        - docker_elk
#    volumes:
#      - my-path:/var/ossec/data
#      - my-path:/etc/postfix
    depends_on:
      - elasticsearch
  logstash:
    image: wazuh/wazuh-logstash
    hostname: logstash
    restart: always
    command: -f /etc/logstash/conf.d/
#    volumes:
#      - my-path:/etc/logstash/conf.d
    links:
     - kibana
     - elasticsearch
    ports:
      - "5000:5000"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
  elasticsearch:
    image: elasticsearch:5.2.2
    hostname: elasticsearch
    restart: always
    command: elasticsearch -E node.name="node-1" -E cluster.name="wazuh" -E network.host=0.0.0.0
#    ports:
#      - "9200:9200"
#      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
#    volumes:
#      - my-path:/usr/share/elasticsearch/data
    networks:
        - docker_elk
  kibana:
    image: wazuh/wazuh-kibana
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    entrypoint: sh wait-for-it.sh elasticsearch

networks:
  docker_elk:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
```
