### ISSUE TITLE
4.3 branch docker compose hostname and services must use slash instead of dot

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#612]
In 4.3 branch, we used the following service and hostname format: 
```
services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.3.0
    hostname: wazuh.manager
```
instead of 4.2 format, it was:
```
services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.3.0
    hostname: wazuh-manager
```
This was due to this issue detection: https://github.com/wazuh/wazuh-packages/issues/1353 but as explained in the latest comments, it's solved in wazuh-packages/pulls/1443. So we need to restore the previous service and hostname format.
