### ISSUE TITLE
Change Wazuh Docker Time for Alerts

### ISSUE THREAD

**Issue by xBounceIT** [wazuh/wazuh-docker#680]
Hi,

i need to change timezone for the Docker version of Wazuh 4.3.4, because alerts via mail have a -2 time date.

I have already set up the container to have the correct date by installing tzdata and configuring it to use Europe/Rome.

I believe the culprit is the /var/ossec/etc/localtime file which still contains the UTC value, but from how is formatted i believe it's something that the Wazuh Server needs to handle by itself.

How can i change the value of it?

Regards,
Daniel D.

**Comment by teddytpc1** [comment]
Hi @xBounceIT.
Can you please perform the following procedure?
1. Move the `/var/ossec/etc/localtime` file:
`mv /var/ossec/etc/localtime /var/ossec/etc/localtime.bak`
2. Copy the `/etc/localtime` file to `/var/ossec/etc/localtime`:
`cp /etc/localtime /var/ossec/etc/localtime`
3. Restart Wazuh manager: you can restart the container or the process using `/var/ossec/bin/wazuh-control restart`.
4. Check the alert logs. The timestamp should be using the new timezone for the new logs.

**Comment by xBounceIT** [comment]
Hi,

after restarting the logs are still using the UTC format.

{"timestamp":"2022-07-13T08:01:21.455+0000","rule":{"level":3,"description":"Ossec server started.","id":"502","firedtimes":1,"mail":true,"groups":["ossec"],"pci_dss":["10.6.1"],"gpg13":["10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.6"],"tsc":["CC7.2","CC7.3"]},"agent":{"id":"000","name":"wazuh.master"},"manager":{"name":"wazuh.master"},"id":"1657699281.492","cluster":{"name":"wazuh","node":"manager"},"full_log":"ossec: Ossec started.","decoder":{"name":"ossec"},"location":"wazuh-monitord"}

**Comment by xBounceIT** [comment]
Hi,

we've managed to fix it by RECREATING and not RESTARTING the container.

What we did was:
1. Modify the docker-compose to mount /etc/localtime in /var/ossec/etc/localtime
2. Stop and remove the containers for both Wazuh nodes
3. Create the containers

Now wazuh logs correctly in the Europe/Rome format.

Regards,
Daniel D.

**Comment by KhizerShareef** [comment]
> 1. Modify the docker-compose to mount /etc/localtime in /var/ossec/etc/localtime

Hey can you share your docker-compose? I am trying to setup the docker-listener to monitor the activities but I am unable to see any real time updates like mentioned in the docs. Later I noticed all the 3 containers logs are using some different time zone as supposed to mine (my local time) and I believe this could be an issue. 

Thanks.

**Comment by xBounceIT** [comment]
> > 1. Modify the docker-compose to mount /etc/localtime in /var/ossec/etc/localtime
> 
> Hey can you share your docker-compose? I am trying to setup the docker-listener to monitor the activities but I am unable to see any real time updates like mentioned in the docs. Later I noticed all the 3 containers logs are using some different time zone as supposed to mine (my local time) and I believe this could be an issue.
> 
> Thanks.

Sure, here it is:

```
version: '3.7'

services:
  wazuh.master:
    image: wazuh/wazuh-manager:4.7.4
    hostname: wazuh.master
    restart: always
    ports:
      - "1515:1515"
      - "514:514/tcp"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh1.indexer:9200
      - INDEXER_USERNAME=USER
      - INDEXER_PASSWORD=PASSWORD
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=USER
      - API_PASSWORD=PASSWORD
    volumes:
      - master-wazuh-api-configuration:/var/ossec/api/configuration
      - master-wazuh-etc:/var/ossec/etc
      - master-wazuh-logs:/var/ossec/logs
      - master-wazuh-queue:/var/ossec/queue
      - master-wazuh-var-multigroups:/var/ossec/var/multigroups
      - master-wazuh-integrations:/var/ossec/integrations
      - master-wazuh-active-response:/var/ossec/active-response/bin
      - master-wazuh-agentless:/var/ossec/agentless
      - master-wazuh-wodles:/var/ossec/wodles
      - master-filebeat-etc:/etc/filebeat
      - master-filebeat-var:/var/lib/filebeat
      - master-filebeat-manifest:/usr/share/filebeat
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.master.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.master-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
      - /etc/localtime:/var/ossec/etc/localtime

  wazuh.worker:
    image: wazuh/wazuh-manager:4.7.4
    hostname: wazuh.worker
    restart: always
    environment:
      - INDEXER_URL=https://wazuh1.indexer:9200
      - INDEXER_USERNAME=USER
      - INDEXER_PASSWORD=PASSWORD
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    volumes:
      - worker-wazuh-api-configuration:/var/ossec/api/configuration
      - worker-wazuh-etc:/var/ossec/etc
      - worker-wazuh-logs:/var/ossec/logs
      - worker-wazuh-queue:/var/ossec/queue
      - worker-wazuh-var-multigroups:/var/ossec/var/multigroups
      - worker-wazuh-integrations:/var/ossec/integrations
      - worker-wazuh-active-response:/var/ossec/active-response/bin
      - worker-wazuh-agentless:/var/ossec/agentless
      - worker-wazuh-wodles:/var/ossec/wodles
      - worker-filebeat-etc:/etc/filebeat
      - worker-filebeat-var:/var/lib/filebeat
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.worker.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.worker-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_worker.conf:/wazuh-config-mount/etc/ossec.conf
      - /etc/localtime:/var/ossec/etc/localtime

  wazuh1.indexer:
    image: wazuh/wazuh-indexer:4.7.4
    hostname: wazuh1.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - TZ=Europe/Rome
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - "bootstrap.memory_lock=true"
      - "JAVA_HOME=/usr/share/wazuh-indexer/jdk"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data-1:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh1.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh1.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh1.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh1.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./config/wazuh_indexer/wazuh1.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./config/wazuh_indexer/ldap/ca.pem:/usr/share/wazuh-indexer/config/certs/ca.pem
      - ./config/wazuh_indexer/config.yml:/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/config.yml

  wazuh2.indexer:
    image: wazuh/wazuh-indexer:4.7.4
    hostname: wazuh2.indexer
    restart: always
    environment:
      - TZ=Europe/Rome
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data-2:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh2.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh2.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh2.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh2.indexer.pem
      - ./config/wazuh_indexer/wazuh2.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml

  wazuh3.indexer:
    image: wazuh/wazuh-indexer:4.7.4
    hostname: wazuh3.indexer
    restart: always
    environment:
      - TZ=Europe/Rome
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data-3:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh3.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh3.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh3.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh3.indexer.pem
      - ./config/wazuh_indexer/wazuh3.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.4
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - TZ=Europe/Rome
      - OPENSEARCH_HOSTS="https://wazuh1.indexer:9200"
      - WAZUH_API_URL="https://wazuh.master"
      - API_USERNAME=USER
      - API_PASSWORD=PASSWORD
    volumes:
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    depends_on:
      - wazuh1.indexer
    links:
      - wazuh1.indexer:wazuh1.indexer
      - wazuh.master:wazuh.master

  nginx:
    image: nginx
    hostname: nginx
    restart: always
    ports:
      - "1514:1514"
    depends_on:
      - wazuh.master
      - wazuh.worker
      - wazuh.dashboard
    links:
      - wazuh.master:wazuh.master
      - wazuh.worker:wazuh.worker
      - wazuh.dashboard:wazuh.dashboard
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

  postfix:
    image: juanluisbaptiste/postfix:1.7.1
    hostname: wazuh-smtp
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=XXXX
      - SMTP_PASSWORD=XXXXX
      - ALWAYS_ADD_MISSING_HEADERS=yes
      - SERVER_HOSTNAME=syncsec.coll

volumes:
  master-wazuh-api-configuration:
  master-wazuh-etc:
  master-wazuh-logs:
  master-wazuh-queue:
  master-wazuh-var-multigroups:
  master-wazuh-integrations:
  master-wazuh-active-response:
  master-wazuh-agentless:
  master-wazuh-wodles:
  master-filebeat-etc:
  master-filebeat-var:
  master-filebeat-manifest:
  worker-wazuh-api-configuration:
  worker-wazuh-etc:
  worker-wazuh-logs:
  worker-wazuh-queue:
  worker-wazuh-var-multigroups:
  worker-wazuh-integrations:
  worker-wazuh-active-response:
  worker-wazuh-agentless:
  worker-wazuh-wodles:
  worker-filebeat-etc:
  worker-filebeat-var:
  wazuh-indexer-data-1:
  wazuh-indexer-data-2:
  wazuh-indexer-data-3:

```
