### ISSUE TITLE
single-node - Authentication failed for admin

### ISSUE THREAD

**Issue by jeevadotnet** [wazuh/wazuh-docker#752]
Wazuh Version: `4.3.10`
Docker Version: `20.10.17`
lsb-release -a: `Ubuntu 20.04.4 LTS`

Good day

Trying to launch a single-node version of Wazuh but getting the following error:
`wazuh.indexer_1    | [2022-11-28T11:04:12,707][WARN ][o.o.s.a.BackendRegistry  ] [wazuh.indexer] Authentication finally failed for admin from 172.19.0.3:58742`

I haven't changed the username & password in the `docker-compose.yml` so still default admin/admin

The only modification I made was:
**Wazuh Manager**
```
  wazuh.manager:
    image: wazuh/wazuh-manager:4.3.10
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
```
port 55000 to 55001 (tried 55001:55000 as well)
```
  wazuh.manager:
    image: wazuh/wazuh-manager:4.3.10
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55001:55001"
```

**Dashboard**
```
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.3.10
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 443:443
```
443 to 5601 (tried 443:5601 as well)
```
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.3.10
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 5601:5601
```
Port changed due to conflicts with Zabbix-Server

Does Wazuh allow for the change of port numbers?

**Comment by rauldpm** [comment]
Hello @jeevadotnet 

Regarding the admin user and the admin password, that user and password do not match the ones used in a single-node deployment, the default password for the admin user is SecretPassword, as specified in the docker-compose.yml file, if in the system you had already made deployment of another previous version, it may be the case that the deployment reuses said volumes if in that previous deployment you changed the password, it will not match the one specified by default.

https://github.com/wazuh/wazuh-docker/blob/15205ada03ebe9b65ddb3ee0c9e2e92221469d63/single-node/docker-compose.yml#L17

```
- INDEXER_USERNAME=admin
- INDEXER_PASSWORD=SecretPassword
```

I have been able to reproduce the `WARNING` you mention by changing `- INDEXER_PASSWORD=SecretPassword` to `- INDEXER_PASSWORD=SecretPassword1`, after which I have obtained the message:

```
[WARN ][o.o.s.a.BackendRegistry  ] [wazuh.indexer] Authentication finally failed for admin from 172.20.0.3:50720
```

Please make sure that the value of `INDEXER_PASSWORD` corresponds to the default value according to the documentation

- https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html

```
The default username and password for the Wazuh dashboard are “admin” and “SecretPassword”.
```

Regarding the ports, the modification for the Wazuh dashboard port should be correct and functional, when accessing the WUI, instead of setting `0.0.0.0`, you should set `0.0.0.0:5601`, which is where the web is being served if it is not redirected to the `443` port.

Regarding port `55000`, since you mention that this port is being used by another application, you need to change only the host port to another that is not being used, for example:

```
- 55555:55000
```
      
Since the file [wazuh.yml](https://github.com/wazuh/wazuh-docker/blob/v4.3.10/single-node/config/wazuh_dashboard/wazuh.yml) file refers to the service, there is no need modify the internal port since it will use the internal Docker network, instead, if the service were external to the Docker network, it would be necessary to use the host port indicated in the docker-compose file
      
Regards, Raúl.

**Comment by jeevadotnet** [comment]
Hi @rauldpm 

Thanks for the detailed reply. I see what the error was, I started to mess around with the password, however it doesn't change if I don't delete the docker volumes first. I've deleted everything including the volumes, changed the password as what you shown.

The documentation states the following:
https://github.com/wazuh/wazuh-docker
![image](https://user-images.githubusercontent.com/12102129/204485815-ee3dcaf3-66a6-42cc-9380-85f431c7a93f.png)

My configs are now the following, deployed behind an NGINX Reverse Proxy, HTTP, with the dashboard being 5601.

```
services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.3.10
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55001:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
```
```
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.3.10
    hostname: wazuh.indexer
    restart: always
    ports:
      - "9200:9200"
```
```
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.3.10
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 5601:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
```

However I have a new issue now that it can't get the API version during the initialization process. It can connect to the API but not get the version

```
INFO: Current API in cookie: [1513629884013]
INFO: Getting API version data...
ERROR: 3002 - Request failed with status code 429

Nov 29, 2022 @ 10:14:31  INFO  Wazuh dashboard index: .kibana
Nov 29, 2022 @ 10:14:31  INFO  App revision: 4311
Nov 29, 2022 @ 10:14:31  INFO  Total RAM: 386873MB
Nov 29, 2022 @ 10:14:32  ERROR  connect ECONNREFUSED 172.19.0.2:55000
Nov 29, 2022 @ 10:40:51  INFO  Wazuh dashboard index: .kibana
Nov 29, 2022 @ 10:40:51  INFO  App revision: 4311
Nov 29, 2022 @ 10:40:51  INFO  Total RAM: 386873MB
Nov 29, 2022 @ 10:40:51  ERROR  connect ECONNREFUSED 172.19.0.3:55000
Nov 29, 2022 @ 10:45:53  ERROR  Request failed with status code 429
Nov 29, 2022 @ 10:45:53  ERROR  Request failed with status code 429
Nov 29, 2022 @ 10:45:53  ERROR  Request failed with status code 429
```

```
wazuh.dashboard_1  | {"type":"response","@timestamp":"2022-11-29T08:53:24Z","tags":[],"pid":39,"method":"post","statusCode":401,"req":{"url":"/api/request","method":"post","headers":{"host":"wazuh.xxxxxxxx.ac.za","x-forwarded-scheme":"http","x-forwarded-proto":"http","x-forwarded-for":"160.119.xxx.xxx","x-real-ip":"160.119.xxx.xxx","connection":"close","content-length":"108","accept":"application/json, text/plain, */*","osd-xsrf":"kibana","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56","content-type":"application/json","origin":"http://wazuh.xxxxxxxx.ac.za","referer":"http://wazuh.xxxxxxxx.ac.za/app/wazuh","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.19.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56","referer":"http://wazuh.xxxxxxxx.ac.za/app/wazuh"},"res":{"statusCode":401,"responseTime":13,"contentLength":9},"message":"POST /api/request 401 13ms - 9.0B"}

wazuh.dashboard_1  | {"type":"response","@timestamp":"2022-11-29T08:53:24Z","tags":[],"pid":39,"method":"post","statusCode":200,"req":{"url":"/api/check-stored-api","method":"post","headers":{"host":"wazuh.xxxxxxxx.ac.za","x-forwarded-scheme":"http","x-forwarded-proto":"http","x-forwarded-for":"160.119.xxx.xxx","x-real-ip":"160.119.xxx.xxx","connection":"close","content-length":"22","accept":"application/json, text/plain, */*","osd-xsrf":"kibana","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56","content-type":"application/json","origin":"http://wazuh.xxxxxxxx.ac.za","referer":"http://wazuh.xxxxxxxx.ac.za/app/wazuh","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.19.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56","referer":"http://wazuh.xxxxxxxx.ac.za/app/wazuh"},"res":{"statusCode":200,"responseTime":700,"contentLength":9},"message":"POST /api/check-stored-api 200 700ms - 9.0B"}
```

I'm deploying it on the internal campus network, with only the dashboard publicly accessible via nginx reverse proxy. However it seems like it is trying to query through the public internet of some sorts.
