### ISSUE TITLE
Add support for Docker in swarm mode

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-docker#840]
Users have [reported](https://github.com/wazuh/wazuh-docker/issues819) to us that the nomenclature we use in the services is not compatible with a deployment in Docker swarm, for this, it is necessary to modify the naming (for example) to `wazuh-(dashboard|indexer|manager)`

It has been verified that with the changes made in the `docker-compose.yml` file, deployment can be done:

```
services:
    wazuh-manager:
    wazuh-indexer:
    wazuh-dashboard:
      links:
        - wazuh-indexer:wazuh.indexer
        - wazuh-manager:wazuh.manager
```

It is necessary to carry out an analysis of the impact of this change on the Docker deployment and make sure that the functionality remains intact as well as the upgrade process from previous versions.
