### ISSUE TITLE
settings are not saved

### ISSUE THREAD

**Issue by xdaass** [wazuh/wazuh-docker#87]
hi, 
after adding one agents (worked), and set password for accessing kibana, my settings lost after running docker-compose down / up
i did commit the image with the new tag and updated the yml file, 
however i only commited the wazuh image, what am i missing ?

**Comment by LuisGi93** [comment]
Hi @xdaass.

I have reproduced your issue. Registering agents and setting the  user/password for accessing Kibana make changes in paths declared as volumes in the Dockerfiles, therefore those changes  won't get saved in a custom image. Registering an agent will alter [/var/ossec/data](https://github.com/wazuh/wazuh-docker/blob/master/wazuh/Dockerfile#L53) and setting  a password for accessing Kibana will alter  [/etc/nginx/conf.d](https://github.com/wazuh/wazuh-docker/blob/master/nginx/Dockerfile#L14).

For preserving the agents that are registered while the wazuh container is up a directory in the host can be specified in the [docker-compose.yml](https://github.com/wazuh/wazuh-docker/blob/master/docker-compose.yml) file. For example:
```yml
services:
  wazuh:
    image: wazuh/wazuh:3.7.2_6.5.4
    #image: wazuh/commitagente:version1
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
#      - "1516:1516"
    networks:
        - docker_elk
          volumes:
                  - /home/user/ossec-data:/var/ossec/data:Z

```
Will save the changes to /var/ossec/data in the Wazuh docker container at the /home/user/ossec-data directory on the host.


A similar approach can be followed for setting the  user/password for accessing Kibana. 

```yml
... 

    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  nginx:
    image: wazuh/wazuh-nginx:3.7.2_6.5.4
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_NAME=newuser
      - NGINX_PWD=newpassword
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/user/nginx-confd:/etc/nginx/conf.d:Z

....
```

It is also possible to specify the user and password  using environment variables as the code block above.
Hope the issue has been clarified a bit.
Regards.
