### ISSUE TITLE
Wazuh dashboard Modules configuration not persisted

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-docker#951]
### Description

The Wazuh dashboard modules configuration is not being persisted after deletion and re-creation of the environment.

### Steps to reproduce

1. Create a single-node environment.
2. Log in to the Wazuh dashboard
3. Go to `Wazuh` > `Settings` > `Modules`.
4. Enable `Virustotal` module.
5. Run `docker-compose down` and then `docker-compose up -d`.
6. Repeat steps 2 and 3. 
7. Check if the `Virustotal` module is still enabled (it shouldn't).

### Tasks
Add a volume for the `/usr/share/wazuh-dashboard/data/wazuh/config` directory in the `docker-compose` file of both deployment options. Add the following lines to the file:

```YAML
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
```

```YAML
  wazuh-dashboard-config:
```

e.g. with the single-node compose file and version `v4.5.0:`

```YAML
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.5.0
    hostname: wazuh.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
      - EXTENSIONS_VIRUSTOTAL=true
    volumes:
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
```

### Validation

1. Create a single-node environment.
2. Log in to the Wazuh dashboard
3. Go to `Wazuh` > `Settings` > `Modules`.
4. Enable `Virustotal` module.
5. Run `docker-compose down` and then `docker-compose up -d`.
6. Repeat steps 2 and 3. 
7. Check if the `Virustotal` module is still enabled.
